//! PP-VILLA-1A — Spec Completion and Grounding Gate.
//!
//! Implements the "Generative Epistemic Loop" contract from ADR-052 §§1–3:
//!
//! * **§1** — A closed four-tag [`GroundingTag`] set that every claim carries,
//!   projected from the existing [`Grounding`] enum in `refinement`.
//! * **§2** — [`SpecCompletionTrace`] and companions: the spec-completion record
//!   that captures a single decision's question, alternatives, materiality, risk,
//!   evidence, and the final selection (resolved or a named [`CorpusGap`]).
//! * **§3** — A mechanical zero-hallucination validator ([`run_grounding_gate`])
//!   that inspects a set of tagged claims and traces and returns a
//!   [`GroundingGateReport`] with pass/fail and individual violations.
//!
//! This module is intentionally self-contained and **does not** modify any
//! existing enum or struct in `refinement.rs` or any other module.

use serde::{Deserialize, Serialize};

use crate::plugins::refinement::Grounding;

// ---------------------------------------------------------------------------
// §1 — Grounding tag (closed projection)
// ---------------------------------------------------------------------------

/// A closed four-value epistemic tag that every non-trivial claim must carry.
///
/// The tag is derived from a [`Grounding`] via [`project_grounding`] or
/// assigned directly at the trace level for user-accepted decisions.
///
/// ADR-052 §1 semantics:
/// * [`SourceBacked`](GroundingTag::SourceBacked) — the value is traced to a
///   corpus artefact: an explicit rule, a catalog row, or an imported document.
/// * [`PolicyBacked`](GroundingTag::PolicyBacked) — the value is generated by
///   a registered recipe or inherited via refinement (authored prior).
/// * [`UserSpecified`](GroundingTag::UserSpecified) — the user reviewed the
///   alternatives and accepted the decision; modeled here at the trace level
///   (see [`SpecCompletionTrace`]) rather than on the underlying [`Grounding`].
/// * [`Unresolved`](GroundingTag::Unresolved) — the claim could not be
///   grounded; it is a visible corpus gap that must be resolved or rejected.
///   An `Unresolved` claim **passes** the gate as a *declared* gap (not a
///   silent hallucination).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[cfg_attr(feature = "model-api", derive(schemars::JsonSchema))]
pub enum GroundingTag {
    /// Traced to a corpus artefact (rule, catalog row, or import).
    SourceBacked,
    /// Generated by a registered recipe or inherited via refinement.
    PolicyBacked,
    /// Reviewed and accepted by the user during spec completion.
    UserSpecified,
    /// Could not be grounded; a named corpus gap must be filed.
    Unresolved,
}

impl GroundingTag {
    /// Human-readable label consistent with the `as_str` convention used
    /// elsewhere in this crate.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::SourceBacked => "SourceBacked",
            Self::PolicyBacked => "PolicyBacked",
            Self::UserSpecified => "UserSpecified",
            Self::Unresolved => "Unresolved",
        }
    }

    /// The canonical ADR-052 wire string for this tag.
    ///
    /// This is the on-the-wire/annotation form the model API's semantic
    /// annotations use (e.g. `SemanticSourceRef.grounding` and
    /// `UnresolvedDecisionRecord.grounding`) — distinct from
    /// [`as_str`](Self::as_str), which is the Rust-variant label. The closed set
    /// is exactly `source-backed | policy-backed | user-specified | unresolved(CorpusGap)`.
    pub fn wire_str(self) -> &'static str {
        match self {
            Self::SourceBacked => "source-backed",
            Self::PolicyBacked => "policy-backed",
            Self::UserSpecified => "user-specified",
            Self::Unresolved => "unresolved(CorpusGap)",
        }
    }

    /// Parse a grounding wire string back into a tag.
    ///
    /// Accepts exactly the four canonical [`wire_str`](Self::wire_str) forms
    /// (whitespace-trimmed). Any other value — empty, free-text, or a malformed
    /// tag — yields `None`, which the gate treats as ungrounded (a likely
    /// hallucination).
    pub fn from_wire(s: &str) -> Option<Self> {
        match s.trim() {
            "source-backed" => Some(Self::SourceBacked),
            "policy-backed" => Some(Self::PolicyBacked),
            "user-specified" => Some(Self::UserSpecified),
            "unresolved(CorpusGap)" => Some(Self::Unresolved),
            _ => None,
        }
    }
}

/// Project an existing [`Grounding`] value onto the closed [`GroundingTag`] set
/// per ADR-052 §1.
///
/// `LLMHeuristic` maps to [`GroundingTag::Unresolved`] because a raw LLM
/// inference is not an authored prior; it must be promoted to a corpus artefact
/// or filed as a gap before it can be treated as grounded.
pub fn project_grounding(g: &Grounding) -> GroundingTag {
    match g {
        Grounding::ExplicitRule(_) | Grounding::CatalogRow(_) | Grounding::Imported(_) => {
            GroundingTag::SourceBacked
        }
        Grounding::GeneratedByRecipe(_) | Grounding::Refined(_) => GroundingTag::PolicyBacked,
        Grounding::LLMHeuristic { .. } => GroundingTag::Unresolved,
    }
}

// ---------------------------------------------------------------------------
// §2 — Spec-completion trace shape
// ---------------------------------------------------------------------------

/// Materiality of a spec-completion decision.
///
/// `High` signals that the decision has a significant impact on cost, safety,
/// or compliance; `Low` means the choice is cosmetic or easily reversible.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "model-api", derive(schemars::JsonSchema))]
pub enum Materiality {
    Low,
    Medium,
    High,
}

/// Risk of getting a spec-completion decision wrong.
///
/// `High` covers irreversible structural decisions or those with safety /
/// regulatory consequences. `Low` covers choices that are trivially correctable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "model-api", derive(schemars::JsonSchema))]
pub enum Risk {
    Low,
    Medium,
    High,
}

/// One alternative considered during a spec-completion question.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "model-api", derive(schemars::JsonSchema))]
pub struct CandidateAlternative {
    /// Short human-readable label.
    pub label: String,
    /// The proposed value (stringified or JSON-encoded).
    pub value: String,
    /// Rationale for why this alternative is plausible.
    pub rationale: String,
    /// Epistemic tag for this candidate.
    pub grounding_tag: GroundingTag,
    /// Evidence references (passage refs, rule ids, etc.) supporting this candidate.
    pub evidence_refs: Vec<String>,
    /// Model confidence in `[0.0, 1.0]`.
    pub confidence: f32,
}

/// The selected outcome of a spec-completion decision.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "model-api", derive(schemars::JsonSchema))]
pub enum SelectedAlternative {
    /// A candidate was chosen (by the model, user, or policy).
    Chosen {
        /// Label of the chosen [`CandidateAlternative`].
        label: String,
    },
    /// No candidate could be grounded; a corpus gap was filed.
    ///
    /// The string value is the [`CorpusGapId`](crate::plugins::corpus_gap::CorpusGapId)
    /// inner string.  Stored as `String` here to remain schema-serialisable
    /// without requiring `JsonSchema` on `CorpusGapId`.  Callers should
    /// construct this from `corpus_gap_id.0`.
    Unresolved {
        /// Stable id of the filed corpus gap (e.g. `"gap-7"`).
        corpus_gap_id: String,
    },
}

/// Full record of a single spec-completion decision.
///
/// One `SpecCompletionTrace` is produced per model-generated default or
/// policy-driven value that touches user-visible design parameters.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "model-api", derive(schemars::JsonSchema))]
pub struct SpecCompletionTrace {
    /// Stable identifier for this question (e.g. `"stair.riser_max_mm"`).
    pub question_id: String,
    /// The natural-language prompt shown to the user when `user_visible` is `true`.
    pub prompt_text: String,
    /// Coarse decision kind — e.g. `"default_selection"`, `"user_override"`,
    /// `"policy_derived"`, `"corpus_gap"`.
    pub decision_kind: String,
    /// How important this decision is to the overall design.
    pub materiality: Materiality,
    /// Risk of making the wrong choice.
    pub risk: Risk,
    /// All candidates the model considered.
    pub alternatives: Vec<CandidateAlternative>,
    /// Which candidate was selected (or the gap that was filed).
    pub selected: SelectedAlternative,
    /// When `true`, the user should be prompted before committing this decision.
    pub user_visible: bool,
    /// Epistemic tag for the selected value.
    ///
    /// For a [`SelectedAlternative::Chosen`] whose selection was explicitly
    /// accepted by the user, set this to [`GroundingTag::UserSpecified`].
    /// For model-selected defaults, project the backing [`Grounding`] via
    /// [`project_grounding`].
    pub grounding_tag: GroundingTag,
    /// Evidence references that support the final selection.
    pub evidence_refs: Vec<String>,
}

/// Returns `true` when the spec-completion gate requires human confirmation
/// before committing the decision.
///
/// Per ADR-052 §2, confirmation is required when:
/// * materiality is `High`, **or**
/// * risk is `High`, **or**
/// * `user_visible` is `true` (policy explicitly marks it as a user choice).
///
/// `Medium`/`Low` combinations are auto-committed by the model.
pub fn should_ask_user(trace: &SpecCompletionTrace) -> bool {
    trace.materiality == Materiality::High || trace.risk == Risk::High || trace.user_visible
}

// ---------------------------------------------------------------------------
// §3 — Zero-hallucination grounding gate
// ---------------------------------------------------------------------------

/// A single violation emitted by [`run_grounding_gate`].
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "model-api", derive(schemars::JsonSchema))]
pub enum GroundingGateFinding {
    /// A claim carries no grounding tag; the path is provided for diagnosis.
    UntaggedClaim {
        /// The slash-delimited claim path (e.g. `"riser_max_mm"`).
        claim_path: String,
    },
    /// A claim carries a grounding *string* that is not one of the closed
    /// wire-format tags — e.g. empty, or free-text like `"seems reasonable"`.
    /// This is the hallucination case the gate exists to catch.
    UngroundedClaim {
        /// The slash-delimited claim path.
        claim_path: String,
        /// The raw, unrecognised grounding string that was supplied.
        raw: String,
    },
}

impl GroundingGateFinding {
    /// Short machine-readable code consistent with `ValidationFinding` codes
    /// elsewhere in the crate.
    pub fn code(&self) -> &'static str {
        match self {
            Self::UntaggedClaim { .. } => "grounding_gate.untagged_claim",
            Self::UngroundedClaim { .. } => "grounding_gate.ungrounded_claim",
        }
    }

    /// Human-readable description of the violation.
    pub fn message(&self) -> String {
        match self {
            Self::UntaggedClaim { claim_path } => {
                format!(
                    "claim '{}' has no grounding tag — it must carry SourceBacked, \
                     PolicyBacked, UserSpecified, or Unresolved(CorpusGap)",
                    claim_path
                )
            }
            Self::UngroundedClaim { claim_path, raw } => {
                format!(
                    "claim '{}' has an unrecognised grounding string '{}' — it must be \
                     one of: source-backed, policy-backed, user-specified, \
                     unresolved(CorpusGap)",
                    claim_path, raw
                )
            }
        }
    }
}

/// The outcome of a [`run_grounding_gate`] call.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "model-api", derive(schemars::JsonSchema))]
pub struct GroundingGateReport {
    /// `true` when all checked claims carry a valid grounding tag.
    pub passed: bool,
    /// All violations found.  Empty when `passed` is `true`.
    pub violations: Vec<GroundingGateFinding>,
}

/// An item presented to the grounding gate for validation.
///
/// The gate accepts any iterator of these; callers may construct them from
/// [`SpecCompletionTrace`] or by directly projecting a [`Grounding`].
#[derive(Debug, Clone, PartialEq)]
pub struct ClaimTagEntry<'a> {
    /// The claim path being validated.
    pub claim_path: &'a str,
    /// The resolved grounding tag, or `None` when the claim has not been tagged.
    pub tag: Option<GroundingTag>,
}

impl<'a> ClaimTagEntry<'a> {
    /// Construct an entry from a concrete tag (always `Some`).
    pub fn tagged(claim_path: &'a str, tag: GroundingTag) -> Self {
        Self {
            claim_path,
            tag: Some(tag),
        }
    }

    /// Construct an entry for an untagged claim.
    pub fn untagged(claim_path: &'a str) -> Self {
        Self {
            claim_path,
            tag: None,
        }
    }
}

/// Validate a set of claim-tag entries against the grounding gate rules
/// (ADR-052 §3).
///
/// **Rules:**
/// * Every claim must carry exactly one tag (i.e. `tag` must be `Some`).
/// * All four tag values — [`GroundingTag::SourceBacked`],
///   [`GroundingTag::PolicyBacked`], [`GroundingTag::UserSpecified`], and
///   [`GroundingTag::Unresolved`] — pass the gate.  An `Unresolved` tag
///   represents a *visible* corpus gap; it is not a hallucination.
/// * An absent (`None`) tag fails with [`GroundingGateFinding::UntaggedClaim`].
///
/// The `_traces` parameter is reserved for future rules that correlate tags
/// against trace evidence (e.g. checking that a `UserSpecified` tag has a
/// matching `SelectedAlternative::Chosen` in the trace set).
pub fn run_grounding_gate<'a>(
    claims: impl IntoIterator<Item = ClaimTagEntry<'a>>,
    _traces: &[SpecCompletionTrace],
) -> GroundingGateReport {
    let mut violations: Vec<GroundingGateFinding> = Vec::new();

    for entry in claims {
        if entry.tag.is_none() {
            violations.push(GroundingGateFinding::UntaggedClaim {
                claim_path: entry.claim_path.to_owned(),
            });
        }
        // All four tag values pass by definition; no further per-tag rules yet.
    }

    let passed = violations.is_empty();
    GroundingGateReport { passed, violations }
}

/// A model annotation presented to the gate: a claim path plus the raw grounding
/// *wire string* the model API recorded for it (e.g. from
/// `SemanticSourceRef.grounding` or `UnresolvedDecisionRecord.grounding`).
#[derive(Debug, Clone, PartialEq)]
pub struct WireClaimEntry<'a> {
    /// The claim path being validated.
    pub claim_path: &'a str,
    /// The raw grounding string recorded on the annotation.
    pub grounding: &'a str,
}

impl<'a> WireClaimEntry<'a> {
    /// Construct a wire-claim entry.
    pub fn new(claim_path: &'a str, grounding: &'a str) -> Self {
        Self {
            claim_path,
            grounding,
        }
    }
}

/// Run the zero-hallucination gate over model annotations whose groundings are
/// wire strings (ADR-052 §3).
///
/// Each grounding is parsed via [`GroundingTag::from_wire`]:
/// * a recognised tag passes — including `unresolved(CorpusGap)`, which is a
///   *declared* gap, not a hallucination;
/// * an empty/whitespace grounding fails as
///   [`GroundingGateFinding::UntaggedClaim`];
/// * any other unrecognised string (free-text, malformed) fails as
///   [`GroundingGateFinding::UngroundedClaim`] — the hallucination case.
///
/// This is the bridge that lets the gate validate real generated artifacts,
/// whose annotations carry grounding as strings rather than typed [`GroundingTag`]s.
pub fn run_grounding_gate_over_wire<'a>(
    claims: impl IntoIterator<Item = WireClaimEntry<'a>>,
) -> GroundingGateReport {
    let mut violations: Vec<GroundingGateFinding> = Vec::new();

    for entry in claims {
        if GroundingTag::from_wire(entry.grounding).is_none() {
            if entry.grounding.trim().is_empty() {
                violations.push(GroundingGateFinding::UntaggedClaim {
                    claim_path: entry.claim_path.to_owned(),
                });
            } else {
                violations.push(GroundingGateFinding::UngroundedClaim {
                    claim_path: entry.claim_path.to_owned(),
                    raw: entry.grounding.to_owned(),
                });
            }
        }
    }

    let passed = violations.is_empty();
    GroundingGateReport { passed, violations }
}

// ---------------------------------------------------------------------------
// §4 — model-api inspection surface (thin, appended in this file)
// ---------------------------------------------------------------------------

/// Serialisable snapshot of a [`GroundingGateReport`] for MCP / model-api
/// consumption.
///
/// Callers that have a full Bevy [`World`] can build this by calling
/// [`run_grounding_gate`] on the entity's tagged claims and passing the result
/// to [`GroundingGateReportInfo::from_report`].
#[cfg_attr(feature = "model-api", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct GroundingGateReportInfo {
    /// Whether all claims passed the gate.
    pub passed: bool,
    /// Serialised violations (if any).
    pub violations: Vec<GroundingGateFindingInfo>,
}

/// Serialisable form of a single [`GroundingGateFinding`].
#[cfg_attr(feature = "model-api", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct GroundingGateFindingInfo {
    pub code: String,
    pub message: String,
}

impl GroundingGateReportInfo {
    /// Convert a [`GroundingGateReport`] into its serialisable form.
    pub fn from_report(report: &GroundingGateReport) -> Self {
        Self {
            passed: report.passed,
            violations: report
                .violations
                .iter()
                .map(|v| GroundingGateFindingInfo {
                    code: v.code().to_owned(),
                    message: v.message(),
                })
                .collect(),
        }
    }
}

/// Serialisable snapshot of a [`SpecCompletionTrace`] for inspection.
#[cfg_attr(feature = "model-api", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SpecCompletionTraceInfo {
    pub question_id: String,
    pub prompt_text: String,
    pub decision_kind: String,
    /// `"Low"`, `"Medium"`, or `"High"`.
    pub materiality: String,
    /// `"Low"`, `"Medium"`, or `"High"`.
    pub risk: String,
    pub grounding_tag: String,
    pub user_visible: bool,
    pub should_ask_user: bool,
    /// `"Chosen:<label>"` or `"Unresolved:<corpus_gap_id>"`.
    pub selected: String,
    pub evidence_refs: Vec<String>,
}

impl SpecCompletionTraceInfo {
    /// Convert a [`SpecCompletionTrace`] into its serialisable form.
    pub fn from_trace(trace: &SpecCompletionTrace) -> Self {
        let materiality = match trace.materiality {
            Materiality::Low => "Low",
            Materiality::Medium => "Medium",
            Materiality::High => "High",
        };
        let risk = match trace.risk {
            Risk::Low => "Low",
            Risk::Medium => "Medium",
            Risk::High => "High",
        };
        let selected = match &trace.selected {
            SelectedAlternative::Chosen { label } => format!("Chosen:{}", label),
            SelectedAlternative::Unresolved { corpus_gap_id } => {
                format!("Unresolved:{}", corpus_gap_id)
            }
        };
        Self {
            question_id: trace.question_id.clone(),
            prompt_text: trace.prompt_text.clone(),
            decision_kind: trace.decision_kind.clone(),
            materiality: materiality.to_owned(),
            risk: risk.to_owned(),
            grounding_tag: trace.grounding_tag.as_str().to_owned(),
            user_visible: trace.user_visible,
            should_ask_user: should_ask_user(trace),
            selected,
            evidence_refs: trace.evidence_refs.clone(),
        }
    }
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::plugins::refinement::{CatalogRowId, Grounding, HeuristicTag, RuleId, SourceRef};

    // --- project_grounding ---

    #[test]
    fn explicit_rule_projects_to_source_backed() {
        let g = Grounding::ExplicitRule(RuleId("BBR_8:22".into()));
        assert_eq!(project_grounding(&g), GroundingTag::SourceBacked);
    }

    #[test]
    fn catalog_row_projects_to_source_backed() {
        let g = Grounding::CatalogRow(CatalogRowId("timber_c24_row_42".into()));
        assert_eq!(project_grounding(&g), GroundingTag::SourceBacked);
    }

    #[test]
    fn imported_projects_to_source_backed() {
        let g = Grounding::Imported(SourceRef("ifc_import_2024.ifc".into()));
        assert_eq!(project_grounding(&g), GroundingTag::SourceBacked);
    }

    #[test]
    fn generated_by_recipe_projects_to_policy_backed() {
        let g = Grounding::GeneratedByRecipe("stair_straight_v1".into());
        assert_eq!(project_grounding(&g), GroundingTag::PolicyBacked);
    }

    #[test]
    fn refined_projects_to_policy_backed() {
        let g = Grounding::Refined(42);
        assert_eq!(project_grounding(&g), GroundingTag::PolicyBacked);
    }

    #[test]
    fn llm_heuristic_projects_to_unresolved() {
        let g = Grounding::LLMHeuristic {
            rationale: "typical Swedish residential riser".into(),
            heuristic_tag: HeuristicTag("domain_prior".into()),
        };
        assert_eq!(project_grounding(&g), GroundingTag::Unresolved);
    }

    // --- should_ask_user ---

    #[test]
    fn high_risk_requires_user_confirmation() {
        let trace = SpecCompletionTrace {
            question_id: "stair.riser_max_mm".into(),
            prompt_text: "What maximum riser height should be used?".into(),
            decision_kind: "default_selection".into(),
            materiality: Materiality::Low,
            risk: Risk::High,
            alternatives: vec![],
            selected: SelectedAlternative::Chosen {
                label: "200mm".into(),
            },
            user_visible: false,
            grounding_tag: GroundingTag::SourceBacked,
            evidence_refs: vec![],
        };
        assert!(should_ask_user(&trace));
    }

    #[test]
    fn low_materiality_low_risk_does_not_require_user_confirmation() {
        let trace = SpecCompletionTrace {
            question_id: "wall.default_color".into(),
            prompt_text: "Default wall color?".into(),
            decision_kind: "default_selection".into(),
            materiality: Materiality::Low,
            risk: Risk::Low,
            alternatives: vec![],
            selected: SelectedAlternative::Chosen {
                label: "white".into(),
            },
            user_visible: false,
            grounding_tag: GroundingTag::PolicyBacked,
            evidence_refs: vec![],
        };
        assert!(!should_ask_user(&trace));
    }

    #[test]
    fn user_visible_flag_forces_confirmation_regardless_of_materiality() {
        let trace = SpecCompletionTrace {
            question_id: "stair.tread_depth_mm".into(),
            prompt_text: "Choose tread depth:".into(),
            decision_kind: "user_override".into(),
            materiality: Materiality::Low,
            risk: Risk::Low,
            alternatives: vec![],
            selected: SelectedAlternative::Chosen {
                label: "300mm".into(),
            },
            user_visible: true,
            grounding_tag: GroundingTag::UserSpecified,
            evidence_refs: vec![],
        };
        assert!(should_ask_user(&trace));
    }

    // --- run_grounding_gate: acceptance case ---

    #[test]
    fn catalog_row_backed_claim_passes_gate() {
        let entries = [ClaimTagEntry::tagged(
            "riser_max_mm",
            GroundingTag::SourceBacked,
        )];
        let report = run_grounding_gate(entries, &[]);
        assert!(report.passed);
        assert!(report.violations.is_empty());
    }

    // --- run_grounding_gate: unresolved passes as visible gap ---

    #[test]
    fn unresolved_selected_alternative_passes_gate_as_visible_gap() {
        // An Unresolved tag represents a filed corpus gap, not a hallucination.
        let trace = SpecCompletionTrace {
            question_id: "envelope.fire_rating".into(),
            prompt_text: "Fire rating class?".into(),
            decision_kind: "corpus_gap".into(),
            materiality: Materiality::High,
            risk: Risk::High,
            alternatives: vec![],
            selected: SelectedAlternative::Unresolved {
                corpus_gap_id: "gap-0".into(),
            },
            user_visible: true,
            grounding_tag: GroundingTag::Unresolved,
            evidence_refs: vec![],
        };

        let entries = [ClaimTagEntry::tagged(
            "envelope.fire_rating",
            GroundingTag::Unresolved,
        )];
        let report = run_grounding_gate(entries, std::slice::from_ref(&trace));
        // Unresolved is a declared gap — the gate passes.
        assert!(report.passed, "unresolved gap should pass the gate");
    }

    // --- run_grounding_gate: untagged claim fails ---

    #[test]
    fn untagged_claim_fails_gate() {
        let entries = [ClaimTagEntry::untagged("wall.thickness_mm")];
        let report = run_grounding_gate(entries, &[]);
        assert!(!report.passed);
        assert_eq!(report.violations.len(), 1);
        assert!(matches!(
            &report.violations[0],
            GroundingGateFinding::UntaggedClaim { claim_path }
            if claim_path == "wall.thickness_mm"
        ));
    }

    // --- run_grounding_gate: mixed tagged and untagged ---

    #[test]
    fn mixed_claims_fails_when_any_untagged() {
        let entries = [
            ClaimTagEntry::tagged("riser_max_mm", GroundingTag::SourceBacked),
            ClaimTagEntry::untagged("tread_depth_mm"),
            ClaimTagEntry::tagged("going_mm", GroundingTag::PolicyBacked),
        ];
        let report = run_grounding_gate(entries, &[]);
        assert!(!report.passed);
        assert_eq!(report.violations.len(), 1);
    }

    // --- run_grounding_gate: all four valid tags pass ---

    #[test]
    fn all_four_tag_variants_pass_gate() {
        let entries = [
            ClaimTagEntry::tagged("a", GroundingTag::SourceBacked),
            ClaimTagEntry::tagged("b", GroundingTag::PolicyBacked),
            ClaimTagEntry::tagged("c", GroundingTag::UserSpecified),
            ClaimTagEntry::tagged("d", GroundingTag::Unresolved),
        ];
        let report = run_grounding_gate(entries, &[]);
        assert!(report.passed);
    }

    // --- GroundingGateReportInfo conversion ---

    #[test]
    fn report_info_from_failing_report_serialises_correctly() {
        let report = GroundingGateReport {
            passed: false,
            violations: vec![GroundingGateFinding::UntaggedClaim {
                claim_path: "wall.thickness_mm".into(),
            }],
        };
        let info = GroundingGateReportInfo::from_report(&report);
        assert!(!info.passed);
        assert_eq!(info.violations.len(), 1);
        assert_eq!(info.violations[0].code, "grounding_gate.untagged_claim");
        assert!(info.violations[0].message.contains("wall.thickness_mm"));
    }

    // --- SpecCompletionTraceInfo conversion ---

    #[test]
    fn trace_info_converts_unresolved_selected_to_string() {
        let trace = SpecCompletionTrace {
            question_id: "fire.class".into(),
            prompt_text: "Which fire class?".into(),
            decision_kind: "corpus_gap".into(),
            materiality: Materiality::High,
            risk: Risk::High,
            alternatives: vec![],
            selected: SelectedAlternative::Unresolved {
                corpus_gap_id: "gap-7".into(),
            },
            user_visible: true,
            grounding_tag: GroundingTag::Unresolved,
            evidence_refs: vec!["BBR_5:532".into()],
        };
        let info = SpecCompletionTraceInfo::from_trace(&trace);
        assert_eq!(info.selected, "Unresolved:gap-7");
        assert_eq!(info.grounding_tag, "Unresolved");
        assert!(info.should_ask_user);
        assert_eq!(info.evidence_refs, vec!["BBR_5:532"]);
    }

    // --- wire_str / from_wire round-trip ---

    #[test]
    fn wire_str_round_trips_for_all_tags() {
        for tag in [
            GroundingTag::SourceBacked,
            GroundingTag::PolicyBacked,
            GroundingTag::UserSpecified,
            GroundingTag::Unresolved,
        ] {
            assert_eq!(GroundingTag::from_wire(tag.wire_str()), Some(tag));
        }
    }

    #[test]
    fn wire_str_matches_adr_052_canonical_strings() {
        assert_eq!(GroundingTag::SourceBacked.wire_str(), "source-backed");
        assert_eq!(GroundingTag::PolicyBacked.wire_str(), "policy-backed");
        assert_eq!(GroundingTag::UserSpecified.wire_str(), "user-specified");
        assert_eq!(GroundingTag::Unresolved.wire_str(), "unresolved(CorpusGap)");
    }

    #[test]
    fn from_wire_trims_and_rejects_unknown_and_empty() {
        assert_eq!(
            GroundingTag::from_wire("  user-specified  "),
            Some(GroundingTag::UserSpecified)
        );
        assert_eq!(GroundingTag::from_wire("seems reasonable"), None);
        assert_eq!(GroundingTag::from_wire(""), None);
        assert_eq!(GroundingTag::from_wire("SourceBacked"), None); // Rust label is not the wire form
    }

    // --- run_grounding_gate_over_wire ---

    #[test]
    fn wire_gate_accepts_real_model_grounding_strings() {
        // Exactly the strings the model API records today (see the model_api
        // `create_box_semantic_annotation_*` test): a user-specified source ref
        // and an unresolved(CorpusGap) decision.
        let entries = [
            WireClaimEntry::new("massing", "user-specified"),
            WireClaimEntry::new("orientation", "unresolved(CorpusGap)"),
            WireClaimEntry::new("stud_spacing_mm", "policy-backed"),
            WireClaimEntry::new("beam_profile", "source-backed"),
        ];
        let report = run_grounding_gate_over_wire(entries);
        assert!(report.passed, "canonical wire strings should pass the gate");
        assert!(report.violations.is_empty());
    }

    #[test]
    fn wire_gate_flags_untagged_and_ungrounded() {
        let entries = [
            WireClaimEntry::new("ok", "source-backed"),
            WireClaimEntry::new("blank", "   "),
            WireClaimEntry::new("guessed", "seems reasonable"),
        ];
        let report = run_grounding_gate_over_wire(entries);
        assert!(!report.passed);
        assert_eq!(report.violations.len(), 2);
        assert!(report.violations.iter().any(|v| matches!(
            v,
            GroundingGateFinding::UntaggedClaim { claim_path } if claim_path == "blank"
        )));
        assert!(report.violations.iter().any(|v| matches!(
            v,
            GroundingGateFinding::UngroundedClaim { claim_path, raw }
                if claim_path == "guessed" && raw == "seems reasonable"
        )));
    }
}
