//! Foundation planting (ADR-034).
//!
//! A `Foundation` is an authored entity that extrudes a closed XZ
//! footprint downward to meet the terrain surface, producing a closed
//! manifold mesh suitable for rendering and boolean operations.
//!
//! Per ADR-034 the foundation is built by:
//!
//! 1. Walking the perimeter, sub-sampling each segment at no more than
//!    `sample_spacing` arc-length intervals.
//! 2. At every sample point, querying the active `TerrainProvider`
//!    for the ground elevation.
//! 3. Emitting a quad strip per perimeter segment whose top edge sits
//!    at `floor_datum` and whose bottom edge follows the sampled
//!    terrain minus `below_grade_margin`.
//! 4. Capping the top with a flat polygon at `floor_datum`.
//! 5. Capping the bottom with a polygon following the sampled terrain.
//!
//! The geometric algorithm (`build_foundation_mesh_from_samples`) is
//! kept as a pure function so it is fully unit-testable without a
//! Bevy world. The Bevy-side machinery is the `Foundation` component,
//! the `TerrainVersion` change-counter resource, and the evaluation
//! system that resolves the footprint, samples the terrain, and emits
//! the resulting `TriangleMesh` + `NeedsMesh`.
//!
//! Limitations of this first cut, called out in ADR-034 §Consequences:
//!
//! - Top and bottom caps are fan-triangulated. This is robust for
//!   convex footprints; non-convex (L-, U-shaped) footprints can
//!   produce overlapping triangles. A constrained-Delaunay or
//!   ear-clipping pass is the natural follow-up.
//! - Wall-loop footprint resolution is stubbed: the recipe exists in
//!   `FoundationFootprint::WallLoop` for forward compatibility but
//!   the evaluation system currently expects an explicit polyline
//!   footprint. A wall-loop resolver lands once arch-core wall
//!   recipes expose a stable XZ-endpoint accessor.

use bevy::math::{DVec2, Vec3};
use bevy::prelude::*;
use serde::{Deserialize, Serialize};

use crate::capability_registry::TerrainProviderRegistry;
use crate::plugins::identity::ElementId;
use crate::plugins::modeling::mesh_generation::{NeedsEvaluation, NeedsMesh};
use crate::plugins::modeling::primitives::TriangleMesh;

/// Footprint reference for a `Foundation`.
///
/// `Polyline` is a closed XZ polyline given as an ordered list of
/// vertices (the closure is implicit; the algorithm wraps from the
/// last back to the first). `WallLoop` references an ordered list of
/// wall element ids whose XZ endpoints form a closed polygon — this
/// variant is wired for forward compatibility but its resolution is
/// deferred until arch-core walls expose stable XZ endpoint
/// accessors.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum FoundationFootprint {
    Polyline(Vec<DVec2>),
    WallLoop(Vec<ElementId>),
}

impl FoundationFootprint {
    /// True when this footprint can be resolved into a vertex list
    /// without further world queries.
    pub fn is_inline(&self) -> bool {
        matches!(self, Self::Polyline(_))
    }
}

/// Authored `Foundation` component (ADR-034).
///
/// Carries the parameters needed to plant a building on the active
/// `TerrainProvider`. The geometry is generated by the evaluation
/// system into a sibling `TriangleMesh` component on the same entity
/// when `NeedsEvaluation` is present.
#[derive(Component, Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Foundation {
    pub footprint: FoundationFootprint,
    /// Y elevation of the interior floor slab, typically 0.0 or the
    /// first-floor finish level.
    pub floor_datum: f64,
    /// How far below the sampled terrain surface the foundation
    /// bottom extends (e.g. 0.3 m to account for footing thickness).
    pub below_grade_margin: f64,
    /// Maximum arc-length interval (in metres) between terrain
    /// elevation samples along each segment. Smaller = more samples,
    /// more accurate, denser mesh.
    pub sample_spacing: f64,
}

impl Foundation {
    /// Construct a polyline-based foundation.
    pub fn polyline(
        perimeter: Vec<DVec2>,
        floor_datum: f64,
        below_grade_margin: f64,
        sample_spacing: f64,
    ) -> Self {
        Self {
            footprint: FoundationFootprint::Polyline(perimeter),
            floor_datum,
            below_grade_margin,
            sample_spacing,
        }
    }
}

/// Per-foundation cache of the `TerrainVersion` value the foundation
/// was last evaluated against. When the live `TerrainVersion`
/// advances past this value the foundation is re-queued with
/// `NeedsEvaluation`.
#[derive(Component, Debug, Clone, Copy, Default, PartialEq, Serialize, Deserialize)]
pub struct LastEvaluatedTerrainVersion(pub u64);

/// Monotonic counter resource: incremented every time terrain data
/// changes (import, sculpt, reload). The `Foundation` evaluation
/// system reads this to decide whether to re-mesh.
#[derive(Resource, Debug, Default, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct TerrainVersion(pub u64);

impl TerrainVersion {
    pub fn bump(&mut self) {
        self.0 = self.0.saturating_add(1);
    }
}

/// Errors produced by foundation evaluation.
#[derive(Debug, Clone, PartialEq)]
pub enum FoundationError {
    /// Footprint had fewer than 3 unique vertices.
    DegenerateFootprint,
    /// Polyline contains a zero-length segment that cannot be sub-
    /// sampled.
    ZeroLengthSegment,
    /// `sample_spacing` was non-positive.
    InvalidSampleSpacing,
    /// Wall-loop footprint resolution is not yet implemented; only
    /// inline polyline footprints are supported in this slice.
    WallLoopUnresolved,
    /// Terrain provider returned no elevation at one of the sample
    /// points (e.g. sample fell outside the terrain extent).
    TerrainOutOfRange { x: f64, z: f64 },
    /// No `TerrainProvider` is registered.
    NoTerrainProvider,
}

impl std::fmt::Display for FoundationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::DegenerateFootprint => write!(f, "footprint must have at least 3 vertices"),
            Self::ZeroLengthSegment => write!(f, "footprint contains a zero-length segment"),
            Self::InvalidSampleSpacing => write!(f, "sample_spacing must be > 0"),
            Self::WallLoopUnresolved => write!(
                f,
                "WallLoop footprints are not yet resolved; use FoundationFootprint::Polyline"
            ),
            Self::TerrainOutOfRange { x, z } => {
                write!(f, "terrain has no elevation at sample ({x}, {z})")
            }
            Self::NoTerrainProvider => write!(f, "no TerrainProvider is registered"),
        }
    }
}

impl std::error::Error for FoundationError {}

/// One sub-sampled perimeter point: its XZ position and the terrain
/// elevation that was observed there.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PerimeterSample {
    pub xz: DVec2,
    pub terrain_y: f64,
}

/// Sub-sample a closed XZ polyline at intervals no greater than
/// `sample_spacing`.
///
/// The closing edge from the last vertex back to the first is included
/// implicitly. Per ADR-034 each sub-interval is no longer than
/// `sample_spacing`; the last sample on each segment lands exactly on
/// the segment's end vertex, so the wrap from segment to segment does
/// not double-up samples.
///
/// Returns the ordered list of XZ sample points around the perimeter,
/// without the closing duplicate.
pub fn subsample_perimeter(
    perimeter: &[DVec2],
    sample_spacing: f64,
) -> Result<Vec<DVec2>, FoundationError> {
    if perimeter.len() < 3 {
        return Err(FoundationError::DegenerateFootprint);
    }
    if !sample_spacing.is_finite() || sample_spacing <= 0.0 {
        return Err(FoundationError::InvalidSampleSpacing);
    }

    let mut samples: Vec<DVec2> = Vec::with_capacity(perimeter.len() * 2);
    for i in 0..perimeter.len() {
        let a = perimeter[i];
        let b = perimeter[(i + 1) % perimeter.len()];
        let segment = b - a;
        let length = segment.length();
        if length == 0.0 {
            return Err(FoundationError::ZeroLengthSegment);
        }
        // Number of sub-intervals (at least 1). We emit `n` points on
        // the *open* segment [a, b) so the wrap from b to the next
        // segment's a does not create a duplicate.
        let n = (length / sample_spacing).ceil().max(1.0) as usize;
        for k in 0..n {
            let t = k as f64 / n as f64;
            samples.push(a + segment * t);
        }
    }
    Ok(samples)
}

/// Build a closed manifold `TriangleMesh` from a perimeter sample
/// sequence and per-sample terrain elevations.
///
/// Inputs are in metres, in the model coordinate frame (y is up).
/// Each perimeter sample produces two mesh vertices: a top vertex at
/// `floor_datum` and a bottom vertex at `terrain_y - below_grade_margin`.
/// Adjacent samples form quads on the perimeter, fan-triangulated
/// into the top and bottom caps.
///
/// The resulting mesh has `2 * N` perimeter vertices plus `2 * N - 4`
/// triangles for the wall, plus `2 * (N - 2)` triangles for the two
/// caps, where `N` is `samples.len()`.
pub fn build_foundation_mesh_from_samples(
    samples: &[PerimeterSample],
    floor_datum: f64,
    below_grade_margin: f64,
) -> Result<TriangleMesh, FoundationError> {
    if samples.len() < 3 {
        return Err(FoundationError::DegenerateFootprint);
    }
    let n = samples.len();
    let mut vertices: Vec<Vec3> = Vec::with_capacity(2 * n);

    // Top vertices: 0..n
    for s in samples {
        vertices.push(Vec3::new(s.xz.x as f32, floor_datum as f32, s.xz.y as f32));
    }
    // Bottom vertices: n..2n
    for s in samples {
        let y = (s.terrain_y - below_grade_margin) as f32;
        vertices.push(Vec3::new(s.xz.x as f32, y, s.xz.y as f32));
    }

    let mut faces: Vec<[u32; 3]> = Vec::new();

    // Perimeter quad strip, two triangles per quad.
    // The footprint is assumed to wind counter-clockwise when viewed
    // from above (y looking down). Outward face normals point away
    // from the interior. Each quad: top[i] - top[i+1] - bot[i+1] -
    // bot[i]; triangulated as (top[i], bot[i], bot[i+1]) and
    // (top[i], bot[i+1], top[i+1]) — outward-facing for CCW winding.
    for i in 0..n {
        let next = (i + 1) % n;
        let top_i = i as u32;
        let top_next = next as u32;
        let bot_i = (i + n) as u32;
        let bot_next = (next + n) as u32;
        faces.push([top_i, bot_i, bot_next]);
        faces.push([top_i, bot_next, top_next]);
    }

    // Top cap: fan from sample[0]. Faces wind opposite to the
    // perimeter so the cap normal points up (out of the foundation).
    for i in 1..(n - 1) {
        faces.push([0, (i + 1) as u32, i as u32]);
    }

    // Bottom cap: fan from sample[0] + n. Wound to face downward.
    let bot0 = n as u32;
    for i in 1..(n - 1) {
        faces.push([bot0, (i + n) as u32, (i + 1 + n) as u32]);
    }

    Ok(TriangleMesh {
        vertices,
        faces,
        normals: None,
        name: Some("foundation".to_string()),
    })
}

/// Bevy plugin: installs `TerrainVersion` and registers the
/// foundation evaluation system.
///
/// Apps that author foundations should add `FoundationPlugin` to their
/// plugin set. The plugin is opt-in because foundation generation
/// requires a `TerrainProviderRegistry` to be populated; an app
/// without terrain capability would gain nothing from running the
/// system.
pub struct FoundationPlugin;

impl Plugin for FoundationPlugin {
    fn build(&self, app: &mut App) {
        if !app.world().contains_resource::<TerrainVersion>() {
            app.init_resource::<TerrainVersion>();
        }
        app.add_systems(Update, evaluate_foundations_system);
    }
}

/// Evaluation system: walks every `Foundation` entity that either has
/// `NeedsEvaluation` set or has a stale `LastEvaluatedTerrainVersion`,
/// resolves the footprint, samples the terrain, builds the mesh, and
/// upserts a `TriangleMesh` + `NeedsMesh` on the same entity.
///
/// Foundations whose evaluation produces an error are left without a
/// `TriangleMesh` and will not render; the error is logged but does
/// not panic.
pub fn evaluate_foundations_system(
    mut commands: Commands,
    terrain_registry: Option<Res<TerrainProviderRegistry>>,
    terrain_version: Res<TerrainVersion>,
    foundations: Query<(
        Entity,
        &Foundation,
        Option<&LastEvaluatedTerrainVersion>,
        Option<&NeedsEvaluation>,
    )>,
    world: &World,
) {
    let provider = match terrain_registry.as_ref().and_then(|r| r.provider()) {
        Some(p) => p,
        None => {
            // No terrain registered → no work; foundations sit idle.
            return;
        }
    };
    for (entity, foundation, last_version, needs_eval) in foundations.iter() {
        let stale = match last_version {
            Some(LastEvaluatedTerrainVersion(v)) => *v != terrain_version.0,
            None => true,
        };
        if !stale && needs_eval.is_none() {
            continue;
        }
        let perimeter = match &foundation.footprint {
            FoundationFootprint::Polyline(verts) => verts.clone(),
            FoundationFootprint::WallLoop(_) => {
                bevy::log::warn!(
                    "Foundation {entity:?}: WallLoop footprints are not yet resolved; skipping",
                );
                continue;
            }
        };
        let samples = match subsample_perimeter(&perimeter, foundation.sample_spacing) {
            Ok(pts) => pts,
            Err(e) => {
                bevy::log::warn!("Foundation {entity:?}: subsample failed: {e}");
                continue;
            }
        };
        let mut sampled: Vec<PerimeterSample> = Vec::with_capacity(samples.len());
        let mut had_terrain_miss = false;
        for xz in samples {
            match provider.elevation_at(world, xz.x as f32, xz.y as f32) {
                Some(y) => sampled.push(PerimeterSample {
                    xz,
                    terrain_y: y as f64,
                }),
                None => {
                    bevy::log::warn!(
                        "Foundation {entity:?}: terrain has no elevation at ({}, {}); skipping",
                        xz.x,
                        xz.y,
                    );
                    had_terrain_miss = true;
                    break;
                }
            }
        }
        if had_terrain_miss {
            continue;
        }
        let mesh = match build_foundation_mesh_from_samples(
            &sampled,
            foundation.floor_datum,
            foundation.below_grade_margin,
        ) {
            Ok(m) => m,
            Err(e) => {
                bevy::log::warn!("Foundation {entity:?}: mesh build failed: {e}");
                continue;
            }
        };
        commands
            .entity(entity)
            .insert(mesh)
            .insert(NeedsMesh)
            .insert(LastEvaluatedTerrainVersion(terrain_version.0))
            .remove::<NeedsEvaluation>();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn square_footprint(half: f64) -> Vec<DVec2> {
        vec![
            DVec2::new(-half, -half),
            DVec2::new(half, -half),
            DVec2::new(half, half),
            DVec2::new(-half, half),
        ]
    }

    fn flat_samples(perimeter: &[DVec2], spacing: f64, terrain_y: f64) -> Vec<PerimeterSample> {
        subsample_perimeter(perimeter, spacing)
            .unwrap()
            .into_iter()
            .map(|xz| PerimeterSample { xz, terrain_y })
            .collect()
    }

    #[test]
    fn subsample_emits_n_points_per_segment_for_unit_square() {
        // 4 unit-length segments × 1 sample each = 4 samples.
        let footprint = square_footprint(0.5);
        let samples = subsample_perimeter(&footprint, 1.0).unwrap();
        assert_eq!(samples.len(), 4);
        // Samples land exactly on the original vertices.
        assert_eq!(samples[0], footprint[0]);
        assert_eq!(samples[1], footprint[1]);
        assert_eq!(samples[2], footprint[2]);
        assert_eq!(samples[3], footprint[3]);
    }

    #[test]
    fn subsample_subdivides_long_segments() {
        // Single segment of length 10 with spacing 2 → 5 sub-points
        // on that segment alone. Total = 5 × 4 segments for a 10-unit
        // square = 20.
        let footprint = square_footprint(5.0);
        let samples = subsample_perimeter(&footprint, 2.0).unwrap();
        assert_eq!(samples.len(), 20);
    }

    #[test]
    fn subsample_rejects_degenerate_footprint() {
        let footprint = vec![DVec2::ZERO, DVec2::new(1.0, 0.0)];
        let err = subsample_perimeter(&footprint, 1.0).unwrap_err();
        assert_eq!(err, FoundationError::DegenerateFootprint);
    }

    #[test]
    fn subsample_rejects_zero_spacing() {
        let footprint = square_footprint(1.0);
        let err = subsample_perimeter(&footprint, 0.0).unwrap_err();
        assert_eq!(err, FoundationError::InvalidSampleSpacing);
    }

    #[test]
    fn subsample_rejects_zero_length_segment() {
        // Two consecutive identical vertices.
        let footprint = vec![
            DVec2::ZERO,
            DVec2::ZERO,
            DVec2::new(1.0, 0.0),
            DVec2::new(0.0, 1.0),
        ];
        let err = subsample_perimeter(&footprint, 1.0).unwrap_err();
        assert_eq!(err, FoundationError::ZeroLengthSegment);
    }

    #[test]
    fn build_mesh_emits_2n_vertices_for_n_samples() {
        let footprint = square_footprint(1.0);
        let samples = flat_samples(&footprint, 1.0, -2.0);
        let mesh = build_foundation_mesh_from_samples(&samples, 0.0, 0.3).unwrap();
        assert_eq!(mesh.vertices.len(), 2 * samples.len());
    }

    #[test]
    fn build_mesh_top_vertices_at_floor_datum() {
        let footprint = square_footprint(2.0);
        let samples = flat_samples(&footprint, 2.0, -3.0);
        let mesh = build_foundation_mesh_from_samples(&samples, 0.5, 0.3).unwrap();
        let n = samples.len();
        for v in &mesh.vertices[..n] {
            assert!((v.y - 0.5).abs() < 1e-5, "top vertex y = {}", v.y);
        }
    }

    #[test]
    fn build_mesh_bottom_vertices_at_terrain_minus_margin() {
        let footprint = square_footprint(2.0);
        let terrain_y = -3.0;
        let margin = 0.4;
        let samples = flat_samples(&footprint, 2.0, terrain_y);
        let mesh = build_foundation_mesh_from_samples(&samples, 0.0, margin).unwrap();
        let n = samples.len();
        for v in &mesh.vertices[n..] {
            assert!(
                (v.y - (terrain_y - margin) as f32).abs() < 1e-5,
                "bottom vertex y = {}",
                v.y,
            );
        }
    }

    #[test]
    fn build_mesh_face_count_matches_formula() {
        // Wall: 2 triangles per perimeter sample (closed loop).
        // Caps: 2 × (n - 2) triangles total.
        let footprint = square_footprint(1.0);
        let samples = flat_samples(&footprint, 1.0, -2.0);
        let n = samples.len();
        let mesh = build_foundation_mesh_from_samples(&samples, 0.0, 0.3).unwrap();
        assert_eq!(mesh.faces.len(), 2 * n + 2 * (n - 2));
    }

    #[test]
    fn build_mesh_rejects_too_few_samples() {
        let samples = vec![PerimeterSample {
            xz: DVec2::ZERO,
            terrain_y: 0.0,
        }];
        let err = build_foundation_mesh_from_samples(&samples, 0.0, 0.3).unwrap_err();
        assert_eq!(err, FoundationError::DegenerateFootprint);
    }

    #[test]
    fn build_mesh_handles_sloped_terrain() {
        // East side at y = -1, west side at y = -3. Bottom vertices
        // should form a stairstep on the perimeter sequence.
        let footprint = square_footprint(2.0);
        let samples: Vec<PerimeterSample> = subsample_perimeter(&footprint, 2.0)
            .unwrap()
            .into_iter()
            .map(|xz| PerimeterSample {
                xz,
                terrain_y: if xz.x > 0.0 { -1.0 } else { -3.0 },
            })
            .collect();
        let mesh = build_foundation_mesh_from_samples(&samples, 0.0, 0.0).unwrap();
        let n = samples.len();
        // Bottom vertices should match the per-sample terrain.
        for (i, s) in samples.iter().enumerate() {
            let v = mesh.vertices[i + n];
            assert!((v.y as f64 - s.terrain_y).abs() < 1e-5);
        }
    }

    #[test]
    fn foundation_polyline_constructor_round_trip() {
        let footprint = square_footprint(2.0);
        let f = Foundation::polyline(footprint.clone(), 0.0, 0.3, 1.0);
        match &f.footprint {
            FoundationFootprint::Polyline(p) => assert_eq!(p, &footprint),
            _ => panic!("expected Polyline"),
        }
        assert_eq!(f.floor_datum, 0.0);
        assert_eq!(f.below_grade_margin, 0.3);
        assert_eq!(f.sample_spacing, 1.0);
    }

    #[test]
    fn foundation_round_trips_through_json() {
        let f = Foundation::polyline(square_footprint(1.5), 0.0, 0.3, 0.5);
        let json = serde_json::to_string(&f).unwrap();
        let parsed: Foundation = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, f);
    }

    #[test]
    fn footprint_is_inline_only_for_polyline() {
        assert!(FoundationFootprint::Polyline(square_footprint(1.0)).is_inline());
        assert!(!FoundationFootprint::WallLoop(vec![]).is_inline());
    }

    #[test]
    fn terrain_version_bumps_monotonically() {
        let mut v = TerrainVersion::default();
        assert_eq!(v.0, 0);
        v.bump();
        assert_eq!(v.0, 1);
        v.bump();
        v.bump();
        assert_eq!(v.0, 3);
    }
}
