//! Foundation planting (ADR-034).
//!
//! A `Foundation` is an authored entity that extrudes a closed XZ
//! footprint downward to meet the terrain surface, producing a closed
//! manifold mesh suitable for rendering and boolean operations.
//!
//! Per ADR-034 the foundation is built by:
//!
//! 1. Walking the perimeter, sub-sampling each segment at no more than
//!    `sample_spacing` arc-length intervals.
//! 2. At every sample point, querying the active `TerrainProvider`
//!    for the ground elevation.
//! 3. Emitting a quad strip per perimeter segment whose top edge sits
//!    at `floor_datum` and whose bottom edge follows the sampled
//!    terrain minus `below_grade_margin`.
//! 4. Capping the top with a flat polygon at `floor_datum`.
//! 5. Capping the bottom with a polygon following the sampled terrain.
//!
//! The geometric algorithm (`build_foundation_mesh_from_samples`) is
//! kept as a pure function so it is fully unit-testable without a
//! Bevy world. The Bevy-side machinery is the `Foundation` component,
//! the `TerrainVersion` change-counter resource, and the evaluation
//! system that resolves the footprint, samples the terrain, and emits
//! the resulting `TriangleMesh` + `NeedsMesh`.
//!
//! ADR-034 slice 4 (this commit) ships the `WallLoop` footprint
//! resolver: foundation evaluation walks the `Vec<ElementId>` wall
//! list, looks each wall up by its `WallEndpoints` component, and
//! threads the endpoints into a closed XZ polyline. Arch-core wall
//! recipes are responsible for inserting `WallEndpoints` on every
//! placed wall occurrence. The component is defined in core so the
//! contract is one-way: core defines the data shape, capability
//! crates supply the data.
//!
//! Earlier limitations from slices 1–3 that remain:
//!
//! - Top and bottom caps are fan-triangulated. This is robust for
//!   convex footprints; non-convex (L-, U-shaped) footprints can
//!   produce overlapping triangles — see `ear_clip_triangulate`
//!   which slice 3 wired in for the cap pass.

use std::any::Any;

use bevy::math::{DVec2, Vec3};
use bevy::prelude::*;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

use crate::authored_entity::{
    invalid_property_error, property_field, scalar_from_json, AuthoredEntity, BoxedEntity,
    HandleInfo, HandleKind, PropertyFieldDef, PropertyValue, PropertyValueKind,
};
use crate::capability_registry::{AuthoredEntityFactory, TerrainProviderRegistry};
use crate::plugins::commands::{despawn_by_element_id, find_entity_by_element_id};
use crate::plugins::identity::{ElementId, ElementIdAllocator};
use crate::plugins::modeling::mesh_generation::{NeedsEvaluation, NeedsMesh};
use crate::plugins::modeling::primitives::TriangleMesh;
use crate::plugins::modeling::triangulate::ear_clip_triangulate;

/// Footprint reference for a `Foundation`.
///
/// `Polyline` is a closed XZ polyline given as an ordered list of
/// vertices (the closure is implicit; the algorithm wraps from the
/// last back to the first). `WallLoop` references an ordered list of
/// wall element ids whose XZ endpoints form a closed polygon — this
/// variant is wired for forward compatibility but its resolution is
/// deferred until arch-core walls expose stable XZ endpoint
/// accessors.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum FoundationFootprint {
    Polyline(Vec<DVec2>),
    WallLoop(Vec<ElementId>),
}

impl FoundationFootprint {
    /// True when this footprint can be resolved into a vertex list
    /// without further world queries.
    pub fn is_inline(&self) -> bool {
        matches!(self, Self::Polyline(_))
    }
}

/// Authored `Foundation` component (ADR-034).
///
/// Carries the parameters needed to plant a building on the active
/// `TerrainProvider`. The geometry is generated by the evaluation
/// system into a sibling `TriangleMesh` component on the same entity
/// when `NeedsEvaluation` is present.
#[derive(Component, Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Foundation {
    pub footprint: FoundationFootprint,
    /// Y elevation of the interior floor slab, typically 0.0 or the
    /// first-floor finish level.
    pub floor_datum: f64,
    /// How far below the sampled terrain surface the foundation
    /// bottom extends (e.g. 0.3 m to account for footing thickness).
    pub below_grade_margin: f64,
    /// Maximum arc-length interval (in metres) between terrain
    /// elevation samples along each segment. Smaller = more samples,
    /// more accurate, denser mesh.
    pub sample_spacing: f64,
}

impl Foundation {
    /// Construct a polyline-based foundation.
    pub fn polyline(
        perimeter: Vec<DVec2>,
        floor_datum: f64,
        below_grade_margin: f64,
        sample_spacing: f64,
    ) -> Self {
        Self {
            footprint: FoundationFootprint::Polyline(perimeter),
            floor_datum,
            below_grade_margin,
            sample_spacing,
        }
    }
}

/// Per-foundation cache of the `TerrainVersion` value the foundation
/// was last evaluated against. When the live `TerrainVersion`
/// advances past this value the foundation is re-queued with
/// `NeedsEvaluation`.
#[derive(Component, Debug, Clone, Copy, Default, PartialEq, Serialize, Deserialize)]
pub struct LastEvaluatedTerrainVersion(pub u64);

/// Monotonic counter resource: incremented every time terrain data
/// changes (import, sculpt, reload). The `Foundation` evaluation
/// system reads this to decide whether to re-mesh.
#[derive(Resource, Debug, Default, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct TerrainVersion(pub u64);

impl TerrainVersion {
    pub fn bump(&mut self) {
        self.0 = self.0.saturating_add(1);
    }
}

/// Per-wall XZ endpoint contract (ADR-034 §5).
///
/// Capability crates that author placed wall occurrences (the
/// architectural light-frame exterior wall recipe being the first
/// example) attach `WallEndpoints` to every wall entity so the
/// `WallLoop` footprint resolver can thread them into a closed
/// polygon. The component carries the start / end XZ in world
/// coordinates as `DVec2(x, z)`. Order is the "authored" order of the
/// wall — the resolver tolerates either traversal direction.
#[derive(Component, Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct WallEndpoints {
    pub start: DVec2,
    pub end: DVec2,
}

impl WallEndpoints {
    pub fn new(start: DVec2, end: DVec2) -> Self {
        Self { start, end }
    }
}

/// Errors produced by foundation evaluation.
#[derive(Debug, Clone, PartialEq)]
pub enum FoundationError {
    /// Footprint had fewer than 3 unique vertices.
    DegenerateFootprint,
    /// Polyline contains a zero-length segment that cannot be sub-
    /// sampled.
    ZeroLengthSegment,
    /// `sample_spacing` was non-positive.
    InvalidSampleSpacing,
    /// `WallLoop` footprint references a wall whose `WallEndpoints`
    /// component is missing. Either the wall id is wrong or the
    /// authoring crate forgot to attach `WallEndpoints`.
    WallEndpointsMissing { wall: ElementId },
    /// `WallLoop` ordered list of walls does not form a connected
    /// loop — the end of wall N does not coincide (within
    /// `wall_loop_tolerance`) with either endpoint of wall N+1.
    WallLoopDisconnected { wall_index: usize },
    /// Last wall's far endpoint does not coincide with the first
    /// wall's start endpoint within tolerance — the loop is open.
    WallLoopOpen,
    /// `WallLoop` had fewer than 3 walls (a closed footprint needs
    /// at least three segments).
    WallLoopTooFewWalls { count: usize },
    /// Terrain provider returned no elevation at one of the sample
    /// points (e.g. sample fell outside the terrain extent).
    TerrainOutOfRange { x: f64, z: f64 },
    /// No `TerrainProvider` is registered.
    NoTerrainProvider,
}

impl std::fmt::Display for FoundationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::DegenerateFootprint => write!(f, "footprint must have at least 3 vertices"),
            Self::ZeroLengthSegment => write!(f, "footprint contains a zero-length segment"),
            Self::InvalidSampleSpacing => write!(f, "sample_spacing must be > 0"),
            Self::WallEndpointsMissing { wall } => write!(
                f,
                "wall {} has no WallEndpoints component; arch-core recipes must attach it on placement",
                wall.0,
            ),
            Self::WallLoopDisconnected { wall_index } => write!(
                f,
                "wall loop disconnected between wall index {} and {}",
                wall_index,
                wall_index + 1
            ),
            Self::WallLoopOpen => write!(
                f,
                "wall loop is open: last wall's endpoint does not return to the first wall's start"
            ),
            Self::WallLoopTooFewWalls { count } => write!(
                f,
                "wall loop has {count} walls; need at least 3 for a closed footprint"
            ),
            Self::TerrainOutOfRange { x, z } => {
                write!(f, "terrain has no elevation at sample ({x}, {z})")
            }
            Self::NoTerrainProvider => write!(f, "no TerrainProvider is registered"),
        }
    }
}

impl std::error::Error for FoundationError {}

/// Default tolerance (in metres) for matching adjacent wall endpoints
/// in [`resolve_wall_loop`]. 1 mm is tight enough to catch authoring
/// errors but lax enough to absorb FP noise from upstream transforms.
pub const DEFAULT_WALL_LOOP_TOLERANCE: f64 = 1.0e-3;

/// Resolve an ordered list of wall element ids into a closed XZ
/// polyline by chaining their endpoints.
///
/// `lookup` returns the start / end XZ pair for each wall id (the
/// `WallEndpoints` data, supplied by the world-side query in
/// [`evaluate_foundations_system`]). The resolver:
///
/// 1. Validates the wall count (≥ 3).
/// 2. Picks the first wall's start such that the chosen end is
///    closest to either endpoint of the second wall.
/// 3. For each subsequent wall, picks the endpoint that matches the
///    previous wall's end within `tolerance`; the other endpoint
///    becomes the new "current" point.
/// 4. Verifies that the final end coincides with the first wall's
///    start.
///
/// On success the returned polyline has one vertex per wall (the
/// "start" of each wall in the chosen traversal direction).
pub fn resolve_wall_loop<F>(
    walls: &[ElementId],
    tolerance: f64,
    mut lookup: F,
) -> Result<Vec<DVec2>, FoundationError>
where
    F: FnMut(ElementId) -> Option<(DVec2, DVec2)>,
{
    if walls.len() < 3 {
        return Err(FoundationError::WallLoopTooFewWalls { count: walls.len() });
    }
    let endpoints: Vec<(DVec2, DVec2)> = walls
        .iter()
        .map(|id| lookup(*id).ok_or(FoundationError::WallEndpointsMissing { wall: *id }))
        .collect::<Result<_, _>>()?;

    // Pick the first wall's traversal direction by checking which
    // endpoint of the first wall is closer to either endpoint of the
    // second wall. The "other" endpoint of the first wall is the
    // loop's first vertex; the "shared" endpoint is the connection
    // point with the second wall.
    let (a0, b0) = endpoints[0];
    let (a1, b1) = endpoints[1];
    let (start, mut current) = if dist(b0, a1) <= tolerance
        || dist(b0, b1) <= tolerance
    {
        (a0, b0)
    } else if dist(a0, a1) <= tolerance || dist(a0, b1) <= tolerance {
        (b0, a0)
    } else {
        return Err(FoundationError::WallLoopDisconnected { wall_index: 0 });
    };

    let mut polyline: Vec<DVec2> = Vec::with_capacity(walls.len());
    polyline.push(start);
    polyline.push(current);

    for i in 1..walls.len() {
        let (a, b) = endpoints[i];
        let next = if dist(current, a) <= tolerance {
            b
        } else if dist(current, b) <= tolerance {
            a
        } else {
            return Err(FoundationError::WallLoopDisconnected { wall_index: i - 1 });
        };
        // Last wall: `next` must coincide with `start`.
        if i == walls.len() - 1 {
            if dist(next, start) > tolerance {
                return Err(FoundationError::WallLoopOpen);
            }
        } else {
            polyline.push(next);
        }
        current = next;
    }

    Ok(polyline)
}

fn dist(a: DVec2, b: DVec2) -> f64 {
    (a - b).length()
}

/// World-side lookup: find the entity whose `ElementId` matches `id`
/// and read its `WallEndpoints`. Returns `None` if either is absent.
fn lookup_wall_endpoints(world: &World, id: ElementId) -> Option<(DVec2, DVec2)> {
    let mut q = world
        .try_query::<(&ElementId, &WallEndpoints)>()?;
    for (eid, ep) in q.iter(world) {
        if *eid == id {
            return Some((ep.start, ep.end));
        }
    }
    None
}

/// One sub-sampled perimeter point: its XZ position and the terrain
/// elevation that was observed there.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PerimeterSample {
    pub xz: DVec2,
    pub terrain_y: f64,
}

/// Sub-sample a closed XZ polyline at intervals no greater than
/// `sample_spacing`.
///
/// The closing edge from the last vertex back to the first is included
/// implicitly. Per ADR-034 each sub-interval is no longer than
/// `sample_spacing`; the last sample on each segment lands exactly on
/// the segment's end vertex, so the wrap from segment to segment does
/// not double-up samples.
///
/// Returns the ordered list of XZ sample points around the perimeter,
/// without the closing duplicate.
pub fn subsample_perimeter(
    perimeter: &[DVec2],
    sample_spacing: f64,
) -> Result<Vec<DVec2>, FoundationError> {
    if perimeter.len() < 3 {
        return Err(FoundationError::DegenerateFootprint);
    }
    if !sample_spacing.is_finite() || sample_spacing <= 0.0 {
        return Err(FoundationError::InvalidSampleSpacing);
    }

    let mut samples: Vec<DVec2> = Vec::with_capacity(perimeter.len() * 2);
    for i in 0..perimeter.len() {
        let a = perimeter[i];
        let b = perimeter[(i + 1) % perimeter.len()];
        let segment = b - a;
        let length = segment.length();
        if length == 0.0 {
            return Err(FoundationError::ZeroLengthSegment);
        }
        // Number of sub-intervals (at least 1). We emit `n` points on
        // the *open* segment [a, b) so the wrap from b to the next
        // segment's a does not create a duplicate.
        let n = (length / sample_spacing).ceil().max(1.0) as usize;
        for k in 0..n {
            let t = k as f64 / n as f64;
            samples.push(a + segment * t);
        }
    }
    Ok(samples)
}

/// Signed area of a 2D polygon (shoelace). Positive when CCW. Used
/// to decide cap normal orientation.
fn projected_signed_area(polygon: &[bevy::math::Vec2]) -> f32 {
    let n = polygon.len();
    if n < 3 {
        return 0.0;
    }
    let mut sum = 0.0_f32;
    for i in 0..n {
        let a = polygon[i];
        let b = polygon[(i + 1) % n];
        sum += a.x * b.y - b.x * a.y;
    }
    sum * 0.5
}

/// Build a closed manifold `TriangleMesh` from a perimeter sample
/// sequence and per-sample terrain elevations.
///
/// Inputs are in metres, in the model coordinate frame (y is up).
/// Each perimeter sample produces two mesh vertices: a top vertex at
/// `floor_datum` and a bottom vertex at `terrain_y - below_grade_margin`.
/// Adjacent samples form quads on the perimeter, fan-triangulated
/// into the top and bottom caps.
///
/// The resulting mesh has `2 * N` perimeter vertices plus `2 * N - 4`
/// triangles for the wall, plus `2 * (N - 2)` triangles for the two
/// caps, where `N` is `samples.len()`.
pub fn build_foundation_mesh_from_samples(
    samples: &[PerimeterSample],
    floor_datum: f64,
    below_grade_margin: f64,
) -> Result<TriangleMesh, FoundationError> {
    if samples.len() < 3 {
        return Err(FoundationError::DegenerateFootprint);
    }
    let n = samples.len();
    let mut vertices: Vec<Vec3> = Vec::with_capacity(2 * n);

    // Top vertices: 0..n
    for s in samples {
        vertices.push(Vec3::new(s.xz.x as f32, floor_datum as f32, s.xz.y as f32));
    }
    // Bottom vertices: n..2n
    for s in samples {
        let y = (s.terrain_y - below_grade_margin) as f32;
        vertices.push(Vec3::new(s.xz.x as f32, y, s.xz.y as f32));
    }

    let mut faces: Vec<[u32; 3]> = Vec::new();

    // Perimeter quad strip, two triangles per quad.
    // The footprint is assumed to wind counter-clockwise when viewed
    // from above (y looking down). Outward face normals point away
    // from the interior. Each quad: top[i] - top[i+1] - bot[i+1] -
    // bot[i]; triangulated as (top[i], bot[i], bot[i+1]) and
    // (top[i], bot[i+1], top[i+1]) — outward-facing for CCW winding.
    for i in 0..n {
        let next = (i + 1) % n;
        let top_i = i as u32;
        let top_next = next as u32;
        let bot_i = (i + n) as u32;
        let bot_next = (next + n) as u32;
        faces.push([top_i, bot_i, bot_next]);
        faces.push([top_i, bot_next, top_next]);
    }

    // Top + bottom caps: triangulate the XZ projection of the
    // perimeter via ear-clipping. This is robust for non-convex
    // (L-, U-shaped) footprints; for convex inputs it produces
    // results equivalent to a fan.
    //
    // The XZ-plane signed area drives normal orientation:
    // - positive (CCW when looking down -y) → top normal points +y
    //   so we keep the ear-clipper's index order for the bottom cap
    //   and reverse for the top.
    // - negative → swap.
    let projected: Vec<bevy::math::Vec2> = samples
        .iter()
        .map(|s| bevy::math::Vec2::new(s.xz.x as f32, s.xz.y as f32))
        .collect();
    let cap_tris = ear_clip_triangulate(&projected);
    let area = projected_signed_area(&projected);
    if cap_tris.is_empty() {
        return Err(FoundationError::DegenerateFootprint);
    }
    let bot_offset = n as u32;
    for tri in cap_tris {
        let [a, b, c] = tri;
        if area > 0.0 {
            // CCW projection → top cap reversed for +y normal,
            // bottom cap kept for -y normal.
            faces.push([a, c, b]);
            faces.push([a + bot_offset, b + bot_offset, c + bot_offset]);
        } else {
            faces.push([a, b, c]);
            faces.push([a + bot_offset, c + bot_offset, b + bot_offset]);
        }
    }

    Ok(TriangleMesh {
        vertices,
        faces,
        normals: None,
        name: Some("foundation".to_string()),
    })
}

/// Bevy plugin: installs `TerrainVersion` and registers the
/// foundation evaluation system.
///
/// Apps that author foundations should add `FoundationPlugin` to their
/// plugin set. The plugin is opt-in because foundation generation
/// requires a `TerrainProviderRegistry` to be populated; an app
/// without terrain capability would gain nothing from running the
/// system.
pub struct FoundationPlugin;

impl Plugin for FoundationPlugin {
    fn build(&self, app: &mut App) {
        if !app.world().contains_resource::<TerrainVersion>() {
            app.init_resource::<TerrainVersion>();
        }
        app.add_systems(Update, evaluate_foundations_system);
    }
}

/// Evaluation system: walks every `Foundation` entity that either has
/// `NeedsEvaluation` set or has a stale `LastEvaluatedTerrainVersion`,
/// resolves the footprint, samples the terrain, builds the mesh, and
/// upserts a `TriangleMesh` + `NeedsMesh` on the same entity.
///
/// Foundations whose evaluation produces an error are left without a
/// `TriangleMesh` and will not render; the error is logged but does
/// not panic.
pub fn evaluate_foundations_system(
    mut commands: Commands,
    terrain_registry: Option<Res<TerrainProviderRegistry>>,
    terrain_version: Res<TerrainVersion>,
    foundations: Query<(
        Entity,
        &Foundation,
        Option<&LastEvaluatedTerrainVersion>,
        Option<&NeedsEvaluation>,
    )>,
    world: &World,
) {
    let provider = match terrain_registry.as_ref().and_then(|r| r.provider()) {
        Some(p) => p,
        None => {
            // No terrain registered → no work; foundations sit idle.
            return;
        }
    };
    for (entity, foundation, last_version, needs_eval) in foundations.iter() {
        let stale = match last_version {
            Some(LastEvaluatedTerrainVersion(v)) => *v != terrain_version.0,
            None => true,
        };
        if !stale && needs_eval.is_none() {
            continue;
        }
        let perimeter = match &foundation.footprint {
            FoundationFootprint::Polyline(verts) => verts.clone(),
            FoundationFootprint::WallLoop(walls) => {
                // Look each wall up in the world and chain the
                // endpoints. `WallEndpoints` is attached by the
                // capability crate that authored the wall (e.g.
                // `talos3d-architecture-core`'s wall recipe).
                let result = resolve_wall_loop(
                    walls,
                    DEFAULT_WALL_LOOP_TOLERANCE,
                    |id| -> Option<(DVec2, DVec2)> {
                        lookup_wall_endpoints(world, id)
                    },
                );
                match result {
                    Ok(verts) => verts,
                    Err(e) => {
                        bevy::log::warn!(
                            "Foundation {entity:?}: wall-loop resolution failed: {e}",
                        );
                        continue;
                    }
                }
            }
        };
        let samples = match subsample_perimeter(&perimeter, foundation.sample_spacing) {
            Ok(pts) => pts,
            Err(e) => {
                bevy::log::warn!("Foundation {entity:?}: subsample failed: {e}");
                continue;
            }
        };
        let mut sampled: Vec<PerimeterSample> = Vec::with_capacity(samples.len());
        let mut had_terrain_miss = false;
        for xz in samples {
            match provider.elevation_at(world, xz.x as f32, xz.y as f32) {
                Some(y) => sampled.push(PerimeterSample {
                    xz,
                    terrain_y: y as f64,
                }),
                None => {
                    bevy::log::warn!(
                        "Foundation {entity:?}: terrain has no elevation at ({}, {}); skipping",
                        xz.x,
                        xz.y,
                    );
                    had_terrain_miss = true;
                    break;
                }
            }
        }
        if had_terrain_miss {
            continue;
        }
        let mesh = match build_foundation_mesh_from_samples(
            &sampled,
            foundation.floor_datum,
            foundation.below_grade_margin,
        ) {
            Ok(m) => m,
            Err(e) => {
                bevy::log::warn!("Foundation {entity:?}: mesh build failed: {e}");
                continue;
            }
        };
        commands
            .entity(entity)
            .insert(mesh)
            .insert(NeedsMesh)
            .insert(LastEvaluatedTerrainVersion(terrain_version.0))
            .remove::<NeedsEvaluation>();
    }
}

// ---------------------------------------------------------------------------
// AuthoredEntity snapshot + MCP factory
// ---------------------------------------------------------------------------

/// MCP-/persistence-facing snapshot of a `Foundation`.
///
/// `Foundation` itself is an ECS component carrying the authored
/// parameters; the snapshot mirrors those parameters in a form that
/// implements [`AuthoredEntity`] so the standard `create_entity` /
/// `get_entity` / `set_property` MCP surface can author and edit
/// foundations from agents.
#[derive(Debug, Clone, PartialEq)]
pub struct FoundationSnapshot {
    pub element_id: ElementId,
    pub footprint: FoundationFootprint,
    pub floor_datum: f64,
    pub below_grade_margin: f64,
    pub sample_spacing: f64,
}

impl FoundationSnapshot {
    fn footprint_centroid_y0(&self) -> Vec3 {
        match &self.footprint {
            FoundationFootprint::Polyline(verts) if !verts.is_empty() => {
                let n = verts.len() as f64;
                let sum: DVec2 = verts.iter().copied().fold(DVec2::ZERO, |a, b| a + b);
                let c = sum / n;
                Vec3::new(c.x as f32, self.floor_datum as f32, c.y as f32)
            }
            _ => Vec3::new(0.0, self.floor_datum as f32, 0.0),
        }
    }

    fn footprint_to_json(&self) -> Value {
        match &self.footprint {
            FoundationFootprint::Polyline(verts) => json!({
                "kind": "polyline",
                "vertices": verts
                    .iter()
                    .map(|v| json!([v.x, v.y]))
                    .collect::<Vec<_>>(),
            }),
            FoundationFootprint::WallLoop(walls) => json!({
                "kind": "wall_loop",
                "walls": walls.iter().map(|e| e.0).collect::<Vec<_>>(),
            }),
        }
    }

    fn footprint_from_json(value: &Value) -> Result<FoundationFootprint, String> {
        let obj = value
            .as_object()
            .ok_or_else(|| "footprint must be an object".to_string())?;
        let kind = obj
            .get("kind")
            .and_then(Value::as_str)
            .ok_or_else(|| "footprint.kind required (\"polyline\" | \"wall_loop\")".to_string())?;
        match kind {
            "polyline" => {
                let arr = obj
                    .get("vertices")
                    .and_then(Value::as_array)
                    .ok_or_else(|| "polyline footprint requires vertices array".to_string())?;
                let mut out = Vec::with_capacity(arr.len());
                for v in arr {
                    let pair = v
                        .as_array()
                        .ok_or_else(|| "vertex must be a [x, z] array".to_string())?;
                    if pair.len() != 2 {
                        return Err("vertex must have exactly 2 components".to_string());
                    }
                    let x = pair[0]
                        .as_f64()
                        .ok_or_else(|| "vertex x must be numeric".to_string())?;
                    let z = pair[1]
                        .as_f64()
                        .ok_or_else(|| "vertex z must be numeric".to_string())?;
                    out.push(DVec2::new(x, z));
                }
                Ok(FoundationFootprint::Polyline(out))
            }
            "wall_loop" => {
                let arr = obj
                    .get("walls")
                    .and_then(Value::as_array)
                    .ok_or_else(|| "wall_loop footprint requires walls array".to_string())?;
                let mut out = Vec::with_capacity(arr.len());
                for v in arr {
                    let id = v
                        .as_u64()
                        .ok_or_else(|| "wall id must be a u64".to_string())?;
                    out.push(ElementId(id));
                }
                Ok(FoundationFootprint::WallLoop(out))
            }
            other => Err(format!(
                "unknown footprint kind '{other}'; expected polyline or wall_loop"
            )),
        }
    }
}

impl AuthoredEntity for FoundationSnapshot {
    fn as_any(&self) -> &dyn Any {
        self
    }

    fn type_name(&self) -> &'static str {
        "foundation"
    }

    fn element_id(&self) -> ElementId {
        self.element_id
    }

    fn label(&self) -> String {
        match &self.footprint {
            FoundationFootprint::Polyline(verts) => {
                format!("Foundation ({}-vertex polyline)", verts.len())
            }
            FoundationFootprint::WallLoop(walls) => {
                format!("Foundation ({}-wall loop)", walls.len())
            }
        }
    }

    fn center(&self) -> Vec3 {
        self.footprint_centroid_y0()
    }

    fn translate_by(&self, delta: Vec3) -> BoxedEntity {
        let mut s = self.clone();
        if let FoundationFootprint::Polyline(ref mut verts) = s.footprint {
            for v in verts.iter_mut() {
                v.x += delta.x as f64;
                v.y += delta.z as f64;
            }
        }
        s.floor_datum += delta.y as f64;
        s.into()
    }

    fn rotate_by(&self, rotation: Quat) -> BoxedEntity {
        let mut s = self.clone();
        if let FoundationFootprint::Polyline(ref mut verts) = s.footprint {
            for v in verts.iter_mut() {
                let world = rotation * Vec3::new(v.x as f32, 0.0, v.y as f32);
                v.x = world.x as f64;
                v.y = world.z as f64;
            }
        }
        s.into()
    }

    fn scale_by(&self, factor: Vec3, center: Vec3) -> BoxedEntity {
        let mut s = self.clone();
        if let FoundationFootprint::Polyline(ref mut verts) = s.footprint {
            let cx = center.x as f64;
            let cz = center.z as f64;
            let fx = factor.x as f64;
            let fz = factor.z as f64;
            for v in verts.iter_mut() {
                v.x = cx + (v.x - cx) * fx;
                v.y = cz + (v.y - cz) * fz;
            }
        }
        // floor_datum scales around center.y
        let cy = center.y as f64;
        let fy = factor.y as f64;
        s.floor_datum = cy + (s.floor_datum - cy) * fy;
        s.below_grade_margin *= fy.abs();
        s.into()
    }

    fn property_fields(&self) -> Vec<PropertyFieldDef> {
        vec![
            property_field(
                "floor_datum",
                PropertyValueKind::Scalar,
                Some(PropertyValue::Scalar(self.floor_datum as f32)),
            ),
            property_field(
                "below_grade_margin",
                PropertyValueKind::Scalar,
                Some(PropertyValue::Scalar(self.below_grade_margin as f32)),
            ),
            property_field(
                "sample_spacing",
                PropertyValueKind::Scalar,
                Some(PropertyValue::Scalar(self.sample_spacing as f32)),
            ),
        ]
    }

    fn set_property_json(&self, property_name: &str, value: &Value) -> Result<BoxedEntity, String> {
        let mut s = self.clone();
        match property_name {
            "floor_datum" => s.floor_datum = scalar_from_json(value)? as f64,
            "below_grade_margin" => {
                let v = scalar_from_json(value)? as f64;
                if v < 0.0 {
                    return Err("below_grade_margin must be >= 0".to_string());
                }
                s.below_grade_margin = v;
            }
            "sample_spacing" => {
                let v = scalar_from_json(value)? as f64;
                if v <= 0.0 {
                    return Err("sample_spacing must be > 0".to_string());
                }
                s.sample_spacing = v;
            }
            "footprint" => {
                s.footprint = Self::footprint_from_json(value)?;
            }
            _ => {
                return Err(invalid_property_error(
                    "foundation",
                    &[
                        "floor_datum",
                        "below_grade_margin",
                        "sample_spacing",
                        "footprint",
                    ],
                ))
            }
        }
        Ok(s.into())
    }

    fn handles(&self) -> Vec<HandleInfo> {
        let mut handles = vec![HandleInfo {
            id: "center".to_string(),
            position: self.footprint_centroid_y0(),
            kind: HandleKind::Center,
            label: "Foundation center".to_string(),
        }];
        if let FoundationFootprint::Polyline(verts) = &self.footprint {
            for (i, v) in verts.iter().enumerate() {
                handles.push(HandleInfo {
                    id: format!("vertex_{i}"),
                    position: Vec3::new(v.x as f32, self.floor_datum as f32, v.y as f32),
                    kind: HandleKind::Vertex,
                    label: format!("Vertex {i}"),
                });
            }
        }
        handles
    }

    fn to_json(&self) -> Value {
        json!({
            "element_id": self.element_id,
            "footprint": self.footprint_to_json(),
            "floor_datum": self.floor_datum,
            "below_grade_margin": self.below_grade_margin,
            "sample_spacing": self.sample_spacing,
        })
    }

    fn apply_to(&self, world: &mut World) {
        let foundation = Foundation {
            footprint: self.footprint.clone(),
            floor_datum: self.floor_datum,
            below_grade_margin: self.below_grade_margin,
            sample_spacing: self.sample_spacing,
        };
        if let Some(entity) = find_entity_by_element_id(world, self.element_id) {
            world
                .entity_mut(entity)
                .insert(foundation)
                .insert(NeedsEvaluation);
        } else {
            world.spawn((self.element_id, foundation, NeedsEvaluation));
        }
    }

    fn remove_from(&self, world: &mut World) {
        despawn_by_element_id(world, self.element_id);
    }

    fn draw_preview(&self, gizmos: &mut Gizmos, color: Color) {
        if let FoundationFootprint::Polyline(verts) = &self.footprint {
            let datum = self.floor_datum as f32;
            for i in 0..verts.len() {
                let a = verts[i];
                let b = verts[(i + 1) % verts.len()];
                gizmos.line(
                    Vec3::new(a.x as f32, datum, a.y as f32),
                    Vec3::new(b.x as f32, datum, b.y as f32),
                    color,
                );
            }
        }
    }

    fn preview_line_count(&self) -> usize {
        match &self.footprint {
            FoundationFootprint::Polyline(verts) => verts.len(),
            FoundationFootprint::WallLoop(_) => 0,
        }
    }

    fn box_clone(&self) -> BoxedEntity {
        self.clone().into()
    }

    fn eq_snapshot(&self, other: &dyn AuthoredEntity) -> bool {
        other.type_name() == "foundation" && other.to_json() == self.to_json()
    }
}

impl From<FoundationSnapshot> for BoxedEntity {
    fn from(snapshot: FoundationSnapshot) -> Self {
        Self(Box::new(snapshot))
    }
}

/// MCP factory: exposes `create_entity { "type": "foundation", ... }`,
/// `get_entity` / `set_property` on existing foundations, and project
/// persistence round-trips.
///
/// Create-request schema:
///
/// ```json
/// {
///   "type": "foundation",
///   "footprint": {
///     "kind": "polyline",
///     "vertices": [[x0, z0], [x1, z1], ...]
///   },
///   "floor_datum": 0.0,
///   "below_grade_margin": 0.3,
///   "sample_spacing": 1.0
/// }
/// ```
pub struct FoundationFactory;

impl AuthoredEntityFactory for FoundationFactory {
    fn type_name(&self) -> &'static str {
        "foundation"
    }

    fn capture_snapshot(
        &self,
        entity_ref: &bevy::ecs::world::EntityRef,
        _world: &World,
    ) -> Option<BoxedEntity> {
        let element_id = *entity_ref.get::<ElementId>()?;
        let foundation = entity_ref.get::<Foundation>()?;
        Some(
            FoundationSnapshot {
                element_id,
                footprint: foundation.footprint.clone(),
                floor_datum: foundation.floor_datum,
                below_grade_margin: foundation.below_grade_margin,
                sample_spacing: foundation.sample_spacing,
            }
            .into(),
        )
    }

    fn from_persisted_json(&self, data: &Value) -> Result<BoxedEntity, String> {
        let element_id: ElementId = serde_json::from_value(
            data.get("element_id")
                .cloned()
                .ok_or_else(|| "Missing element_id".to_string())?,
        )
        .map_err(|e| e.to_string())?;
        let footprint = data
            .get("footprint")
            .ok_or_else(|| "Missing footprint".to_string())
            .and_then(FoundationSnapshot::footprint_from_json)?;
        let floor_datum = data
            .get("floor_datum")
            .and_then(Value::as_f64)
            .ok_or_else(|| "Missing floor_datum".to_string())?;
        let below_grade_margin = data
            .get("below_grade_margin")
            .and_then(Value::as_f64)
            .unwrap_or(0.3);
        let sample_spacing = data
            .get("sample_spacing")
            .and_then(Value::as_f64)
            .unwrap_or(1.0);
        Ok(FoundationSnapshot {
            element_id,
            footprint,
            floor_datum,
            below_grade_margin,
            sample_spacing,
        }
        .into())
    }

    fn from_create_request(&self, world: &World, request: &Value) -> Result<BoxedEntity, String> {
        let obj = request
            .as_object()
            .ok_or_else(|| "create_entity expects a JSON object".to_string())?;
        let element_id = world
            .get_resource::<ElementIdAllocator>()
            .ok_or_else(|| "ElementIdAllocator not available".to_string())?
            .next_id();
        let footprint = obj
            .get("footprint")
            .ok_or_else(|| {
                "foundation create_entity requires \"footprint\" with kind + vertices".to_string()
            })
            .and_then(FoundationSnapshot::footprint_from_json)?;
        let floor_datum = obj
            .get("floor_datum")
            .and_then(Value::as_f64)
            .unwrap_or(0.0);
        let below_grade_margin = obj
            .get("below_grade_margin")
            .and_then(Value::as_f64)
            .unwrap_or(0.3);
        if below_grade_margin < 0.0 {
            return Err("below_grade_margin must be >= 0".to_string());
        }
        let sample_spacing = obj
            .get("sample_spacing")
            .and_then(Value::as_f64)
            .unwrap_or(1.0);
        if !(sample_spacing > 0.0) {
            return Err("sample_spacing must be > 0".to_string());
        }
        Ok(FoundationSnapshot {
            element_id,
            footprint,
            floor_datum,
            below_grade_margin,
            sample_spacing,
        }
        .into())
    }

    fn dependency_edges(
        &self,
        world: &World,
        entity: Entity,
    ) -> crate::plugins::modeling::dependency_graph::EntityDependencies {
        use crate::plugins::modeling::dependency_graph::EntityDependencies;
        let Some(foundation) = world.get::<Foundation>(entity) else {
            return EntityDependencies::empty();
        };
        // Polyline footprints carry no structural edges; the
        // perimeter is fully self-contained data on the component.
        // WallLoop footprints depend on every wall in the loop.
        match &foundation.footprint {
            FoundationFootprint::Polyline(_) => EntityDependencies::empty(),
            FoundationFootprint::WallLoop(walls) => {
                let mut deps = EntityDependencies::empty();
                for wall in walls {
                    deps = deps.with_edge(*wall, "foundation_wall_loop");
                }
                deps
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn square_footprint(half: f64) -> Vec<DVec2> {
        vec![
            DVec2::new(-half, -half),
            DVec2::new(half, -half),
            DVec2::new(half, half),
            DVec2::new(-half, half),
        ]
    }

    fn flat_samples(perimeter: &[DVec2], spacing: f64, terrain_y: f64) -> Vec<PerimeterSample> {
        subsample_perimeter(perimeter, spacing)
            .unwrap()
            .into_iter()
            .map(|xz| PerimeterSample { xz, terrain_y })
            .collect()
    }

    #[test]
    fn subsample_emits_n_points_per_segment_for_unit_square() {
        // 4 unit-length segments × 1 sample each = 4 samples.
        let footprint = square_footprint(0.5);
        let samples = subsample_perimeter(&footprint, 1.0).unwrap();
        assert_eq!(samples.len(), 4);
        // Samples land exactly on the original vertices.
        assert_eq!(samples[0], footprint[0]);
        assert_eq!(samples[1], footprint[1]);
        assert_eq!(samples[2], footprint[2]);
        assert_eq!(samples[3], footprint[3]);
    }

    #[test]
    fn subsample_subdivides_long_segments() {
        // Single segment of length 10 with spacing 2 → 5 sub-points
        // on that segment alone. Total = 5 × 4 segments for a 10-unit
        // square = 20.
        let footprint = square_footprint(5.0);
        let samples = subsample_perimeter(&footprint, 2.0).unwrap();
        assert_eq!(samples.len(), 20);
    }

    #[test]
    fn subsample_rejects_degenerate_footprint() {
        let footprint = vec![DVec2::ZERO, DVec2::new(1.0, 0.0)];
        let err = subsample_perimeter(&footprint, 1.0).unwrap_err();
        assert_eq!(err, FoundationError::DegenerateFootprint);
    }

    #[test]
    fn subsample_rejects_zero_spacing() {
        let footprint = square_footprint(1.0);
        let err = subsample_perimeter(&footprint, 0.0).unwrap_err();
        assert_eq!(err, FoundationError::InvalidSampleSpacing);
    }

    #[test]
    fn subsample_rejects_zero_length_segment() {
        // Two consecutive identical vertices.
        let footprint = vec![
            DVec2::ZERO,
            DVec2::ZERO,
            DVec2::new(1.0, 0.0),
            DVec2::new(0.0, 1.0),
        ];
        let err = subsample_perimeter(&footprint, 1.0).unwrap_err();
        assert_eq!(err, FoundationError::ZeroLengthSegment);
    }

    #[test]
    fn build_mesh_emits_2n_vertices_for_n_samples() {
        let footprint = square_footprint(1.0);
        let samples = flat_samples(&footprint, 1.0, -2.0);
        let mesh = build_foundation_mesh_from_samples(&samples, 0.0, 0.3).unwrap();
        assert_eq!(mesh.vertices.len(), 2 * samples.len());
    }

    #[test]
    fn build_mesh_top_vertices_at_floor_datum() {
        let footprint = square_footprint(2.0);
        let samples = flat_samples(&footprint, 2.0, -3.0);
        let mesh = build_foundation_mesh_from_samples(&samples, 0.5, 0.3).unwrap();
        let n = samples.len();
        for v in &mesh.vertices[..n] {
            assert!((v.y - 0.5).abs() < 1e-5, "top vertex y = {}", v.y);
        }
    }

    #[test]
    fn build_mesh_bottom_vertices_at_terrain_minus_margin() {
        let footprint = square_footprint(2.0);
        let terrain_y = -3.0;
        let margin = 0.4;
        let samples = flat_samples(&footprint, 2.0, terrain_y);
        let mesh = build_foundation_mesh_from_samples(&samples, 0.0, margin).unwrap();
        let n = samples.len();
        for v in &mesh.vertices[n..] {
            assert!(
                (v.y - (terrain_y - margin) as f32).abs() < 1e-5,
                "bottom vertex y = {}",
                v.y,
            );
        }
    }

    #[test]
    fn build_mesh_face_count_matches_formula() {
        // Wall: 2 triangles per perimeter sample (closed loop).
        // Caps: 2 × (n - 2) triangles total.
        let footprint = square_footprint(1.0);
        let samples = flat_samples(&footprint, 1.0, -2.0);
        let n = samples.len();
        let mesh = build_foundation_mesh_from_samples(&samples, 0.0, 0.3).unwrap();
        assert_eq!(mesh.faces.len(), 2 * n + 2 * (n - 2));
    }

    #[test]
    fn build_mesh_rejects_too_few_samples() {
        let samples = vec![PerimeterSample {
            xz: DVec2::ZERO,
            terrain_y: 0.0,
        }];
        let err = build_foundation_mesh_from_samples(&samples, 0.0, 0.3).unwrap_err();
        assert_eq!(err, FoundationError::DegenerateFootprint);
    }

    #[test]
    fn build_mesh_handles_non_convex_l_shape() {
        // L-shaped footprint:
        //   (0,0) → (4,0) → (4,2) → (2,2) → (2,4) → (0,4) → close
        let footprint = vec![
            DVec2::new(0.0, 0.0),
            DVec2::new(4.0, 0.0),
            DVec2::new(4.0, 2.0),
            DVec2::new(2.0, 2.0),
            DVec2::new(2.0, 4.0),
            DVec2::new(0.0, 4.0),
        ];
        let samples: Vec<PerimeterSample> = subsample_perimeter(&footprint, 2.0)
            .unwrap()
            .into_iter()
            .map(|xz| PerimeterSample { xz, terrain_y: -1.5 })
            .collect();
        let n = samples.len();
        let mesh = build_foundation_mesh_from_samples(&samples, 0.0, 0.3).unwrap();
        // Vertices: 2N (top + bottom rings).
        assert_eq!(mesh.vertices.len(), 2 * n);
        // Wall: 2N triangles. Caps: 2 × (N - 2). Same arithmetic as
        // the convex case because the ear-clipper outputs n-2
        // triangles for any simple polygon.
        assert_eq!(mesh.faces.len(), 2 * n + 2 * (n - 2));
    }

    #[test]
    fn build_mesh_handles_sloped_terrain() {
        // East side at y = -1, west side at y = -3. Bottom vertices
        // should form a stairstep on the perimeter sequence.
        let footprint = square_footprint(2.0);
        let samples: Vec<PerimeterSample> = subsample_perimeter(&footprint, 2.0)
            .unwrap()
            .into_iter()
            .map(|xz| PerimeterSample {
                xz,
                terrain_y: if xz.x > 0.0 { -1.0 } else { -3.0 },
            })
            .collect();
        let mesh = build_foundation_mesh_from_samples(&samples, 0.0, 0.0).unwrap();
        let n = samples.len();
        // Bottom vertices should match the per-sample terrain.
        for (i, s) in samples.iter().enumerate() {
            let v = mesh.vertices[i + n];
            assert!((v.y as f64 - s.terrain_y).abs() < 1e-5);
        }
    }

    #[test]
    fn foundation_polyline_constructor_round_trip() {
        let footprint = square_footprint(2.0);
        let f = Foundation::polyline(footprint.clone(), 0.0, 0.3, 1.0);
        match &f.footprint {
            FoundationFootprint::Polyline(p) => assert_eq!(p, &footprint),
            _ => panic!("expected Polyline"),
        }
        assert_eq!(f.floor_datum, 0.0);
        assert_eq!(f.below_grade_margin, 0.3);
        assert_eq!(f.sample_spacing, 1.0);
    }

    #[test]
    fn foundation_round_trips_through_json() {
        let f = Foundation::polyline(square_footprint(1.5), 0.0, 0.3, 0.5);
        let json = serde_json::to_string(&f).unwrap();
        let parsed: Foundation = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, f);
    }

    #[test]
    fn footprint_is_inline_only_for_polyline() {
        assert!(FoundationFootprint::Polyline(square_footprint(1.0)).is_inline());
        assert!(!FoundationFootprint::WallLoop(vec![]).is_inline());
    }

    #[test]
    fn terrain_version_bumps_monotonically() {
        let mut v = TerrainVersion::default();
        assert_eq!(v.0, 0);
        v.bump();
        assert_eq!(v.0, 1);
        v.bump();
        v.bump();
        assert_eq!(v.0, 3);
    }

    // -- Snapshot / factory tests ------------------------------------

    fn sample_snapshot() -> FoundationSnapshot {
        FoundationSnapshot {
            element_id: ElementId(42),
            footprint: FoundationFootprint::Polyline(square_footprint(2.0)),
            floor_datum: 0.5,
            below_grade_margin: 0.3,
            sample_spacing: 1.0,
        }
    }

    #[test]
    fn snapshot_to_json_round_trips_via_factory() {
        let snapshot = sample_snapshot();
        let json = snapshot.to_json();
        let parsed = FoundationFactory.from_persisted_json(&json).unwrap();
        assert!(snapshot.eq_snapshot(&*parsed.0));
    }

    #[test]
    fn factory_create_request_assigns_fresh_element_id() {
        let mut world = World::new();
        world.insert_resource(ElementIdAllocator::default());
        let request = json!({
            "type": "foundation",
            "footprint": {
                "kind": "polyline",
                "vertices": [[-2.0, -2.0], [2.0, -2.0], [2.0, 2.0], [-2.0, 2.0]]
            },
            "floor_datum": 0.0,
            "below_grade_margin": 0.3,
            "sample_spacing": 1.0
        });
        let boxed = FoundationFactory
            .from_create_request(&world, &request)
            .unwrap();
        let snapshot = boxed.0.as_any().downcast_ref::<FoundationSnapshot>().unwrap();
        // The allocator started at 0; the first call returns 0, then 1, ...
        // After this call the allocator should be advanced to 1.
        assert_eq!(snapshot.element_id.0, 0);
        assert_eq!(world.resource::<ElementIdAllocator>().next_value(), 1);
        assert_eq!(snapshot.floor_datum, 0.0);
        assert_eq!(snapshot.below_grade_margin, 0.3);
    }

    #[test]
    fn factory_create_request_rejects_negative_below_grade_margin() {
        let mut world = World::new();
        world.insert_resource(ElementIdAllocator::default());
        let request = json!({
            "type": "foundation",
            "footprint": {
                "kind": "polyline",
                "vertices": [[0.0, 0.0], [1.0, 0.0], [1.0, 1.0], [0.0, 1.0]]
            },
            "below_grade_margin": -0.1,
        });
        let err = FoundationFactory
            .from_create_request(&world, &request)
            .unwrap_err();
        assert!(err.contains("below_grade_margin"));
    }

    #[test]
    fn factory_create_request_rejects_zero_sample_spacing() {
        let mut world = World::new();
        world.insert_resource(ElementIdAllocator::default());
        let request = json!({
            "type": "foundation",
            "footprint": {
                "kind": "polyline",
                "vertices": [[0.0, 0.0], [1.0, 0.0], [1.0, 1.0], [0.0, 1.0]]
            },
            "sample_spacing": 0.0,
        });
        let err = FoundationFactory
            .from_create_request(&world, &request)
            .unwrap_err();
        assert!(err.contains("sample_spacing"));
    }

    #[test]
    fn factory_create_request_requires_footprint() {
        let mut world = World::new();
        world.insert_resource(ElementIdAllocator::default());
        let request = json!({ "type": "foundation" });
        let err = FoundationFactory
            .from_create_request(&world, &request)
            .unwrap_err();
        assert!(err.contains("footprint"));
    }

    #[test]
    fn footprint_from_json_supports_wall_loop_kind() {
        let json = json!({ "kind": "wall_loop", "walls": [10, 11, 12, 13] });
        let footprint = FoundationSnapshot::footprint_from_json(&json).unwrap();
        match footprint {
            FoundationFootprint::WallLoop(walls) => {
                assert_eq!(walls.len(), 4);
                assert_eq!(walls[0].0, 10);
            }
            _ => panic!("expected WallLoop"),
        }
    }

    #[test]
    fn snapshot_translate_by_shifts_polyline_and_datum() {
        let snapshot = sample_snapshot();
        let translated = snapshot.translate_by(Vec3::new(10.0, 1.5, -3.0));
        let s = translated
            .0
            .as_any()
            .downcast_ref::<FoundationSnapshot>()
            .unwrap();
        if let FoundationFootprint::Polyline(verts) = &s.footprint {
            for (orig, moved) in square_footprint(2.0).iter().zip(verts.iter()) {
                assert!((moved.x - orig.x - 10.0).abs() < 1e-6);
                assert!((moved.y - orig.y - (-3.0)).abs() < 1e-6);
            }
        } else {
            panic!("expected Polyline");
        }
        assert!((s.floor_datum - 2.0).abs() < 1e-6);
    }

    #[test]
    fn snapshot_apply_to_inserts_foundation_and_needs_evaluation() {
        let mut world = World::new();
        world.insert_resource(ElementIdAllocator::default());
        let snapshot = sample_snapshot();
        snapshot.apply_to(&mut world);
        // Find the entity by element id.
        let entity = find_entity_by_element_id(&mut world, snapshot.element_id).unwrap();
        let f = world.get::<Foundation>(entity).unwrap();
        assert_eq!(f.floor_datum, snapshot.floor_datum);
        assert!(world.get::<NeedsEvaluation>(entity).is_some());
    }

    #[test]
    fn snapshot_set_property_validates_below_grade_margin_non_negative() {
        let snapshot = sample_snapshot();
        let err = snapshot
            .set_property_json("below_grade_margin", &json!(-0.1))
            .unwrap_err();
        assert!(err.contains(">= 0"));
    }

    #[test]
    fn snapshot_set_property_validates_sample_spacing_positive() {
        let snapshot = sample_snapshot();
        let err = snapshot
            .set_property_json("sample_spacing", &json!(0.0))
            .unwrap_err();
        assert!(err.contains("> 0"));
    }

    #[test]
    fn snapshot_handles_one_per_polyline_vertex_plus_center() {
        let snapshot = sample_snapshot();
        let handles = snapshot.handles();
        // 1 center + 4 polyline vertex handles for the unit square.
        assert_eq!(handles.len(), 5);
        assert_eq!(handles[0].id, "center");
        assert_eq!(handles[1].id, "vertex_0");
    }

    // ---- WallLoop resolver tests (ADR-034 slice 4) -----------------

    fn unit_square_walls() -> Vec<((u64, DVec2, DVec2))> {
        // 4 walls forming a 1x1 square at the origin.
        vec![
            (10, DVec2::new(0.0, 0.0), DVec2::new(1.0, 0.0)),
            (11, DVec2::new(1.0, 0.0), DVec2::new(1.0, 1.0)),
            (12, DVec2::new(1.0, 1.0), DVec2::new(0.0, 1.0)),
            (13, DVec2::new(0.0, 1.0), DVec2::new(0.0, 0.0)),
        ]
    }

    fn lookup_for(walls: &[(u64, DVec2, DVec2)]) -> impl Fn(ElementId) -> Option<(DVec2, DVec2)> + '_ {
        move |id: ElementId| -> Option<(DVec2, DVec2)> {
            walls
                .iter()
                .find(|(wid, _, _)| *wid == id.0)
                .map(|(_, a, b)| (*a, *b))
        }
    }

    #[test]
    fn resolve_wall_loop_unit_square_returns_four_vertices() {
        let walls = unit_square_walls();
        let ids: Vec<ElementId> = walls.iter().map(|(id, _, _)| ElementId(*id)).collect();
        let lookup = lookup_for(&walls);
        let polyline =
            resolve_wall_loop(&ids, DEFAULT_WALL_LOOP_TOLERANCE, lookup).unwrap();
        assert_eq!(polyline.len(), 4);
        // Polyline starts somewhere on the loop; rotate so we know
        // the first vertex.
        assert!(polyline.contains(&DVec2::new(0.0, 0.0)));
        assert!(polyline.contains(&DVec2::new(1.0, 0.0)));
        assert!(polyline.contains(&DVec2::new(1.0, 1.0)));
        assert!(polyline.contains(&DVec2::new(0.0, 1.0)));
    }

    #[test]
    fn resolve_wall_loop_tolerates_reversed_walls() {
        // Same square but wall 11 is authored backward (1,1)→(1,0).
        let walls = vec![
            (10, DVec2::new(0.0, 0.0), DVec2::new(1.0, 0.0)),
            (11, DVec2::new(1.0, 1.0), DVec2::new(1.0, 0.0)),
            (12, DVec2::new(1.0, 1.0), DVec2::new(0.0, 1.0)),
            (13, DVec2::new(0.0, 1.0), DVec2::new(0.0, 0.0)),
        ];
        let ids: Vec<ElementId> = walls.iter().map(|(id, _, _)| ElementId(*id)).collect();
        let lookup = lookup_for(&walls);
        let polyline =
            resolve_wall_loop(&ids, DEFAULT_WALL_LOOP_TOLERANCE, lookup).unwrap();
        assert_eq!(polyline.len(), 4);
    }

    #[test]
    fn resolve_wall_loop_rejects_too_few_walls() {
        let walls = vec![
            (10, DVec2::new(0.0, 0.0), DVec2::new(1.0, 0.0)),
            (11, DVec2::new(1.0, 0.0), DVec2::new(0.0, 0.0)),
        ];
        let ids: Vec<ElementId> = walls.iter().map(|(id, _, _)| ElementId(*id)).collect();
        let lookup = lookup_for(&walls);
        let err = resolve_wall_loop(&ids, DEFAULT_WALL_LOOP_TOLERANCE, lookup).unwrap_err();
        assert_eq!(err, FoundationError::WallLoopTooFewWalls { count: 2 });
    }

    #[test]
    fn resolve_wall_loop_reports_missing_wall_endpoints() {
        let ids = vec![ElementId(99), ElementId(98), ElementId(97)];
        let err = resolve_wall_loop(&ids, DEFAULT_WALL_LOOP_TOLERANCE, |_| None).unwrap_err();
        assert_eq!(
            err,
            FoundationError::WallEndpointsMissing { wall: ElementId(99) }
        );
    }

    #[test]
    fn resolve_wall_loop_detects_disconnected_walls() {
        // Wall 11 doesn't touch wall 10 anywhere.
        let walls = vec![
            (10, DVec2::new(0.0, 0.0), DVec2::new(1.0, 0.0)),
            (11, DVec2::new(5.0, 5.0), DVec2::new(5.0, 6.0)),
            (12, DVec2::new(5.0, 6.0), DVec2::new(0.0, 6.0)),
            (13, DVec2::new(0.0, 6.0), DVec2::new(0.0, 0.0)),
        ];
        let ids: Vec<ElementId> = walls.iter().map(|(id, _, _)| ElementId(*id)).collect();
        let lookup = lookup_for(&walls);
        let err = resolve_wall_loop(&ids, DEFAULT_WALL_LOOP_TOLERANCE, lookup).unwrap_err();
        assert_eq!(err, FoundationError::WallLoopDisconnected { wall_index: 0 });
    }

    #[test]
    fn resolve_wall_loop_detects_open_loop() {
        // Three walls that touch end-to-end but the third doesn't
        // close back to wall 1.
        let walls = vec![
            (10, DVec2::new(0.0, 0.0), DVec2::new(1.0, 0.0)),
            (11, DVec2::new(1.0, 0.0), DVec2::new(1.0, 1.0)),
            (12, DVec2::new(1.0, 1.0), DVec2::new(2.0, 2.0)),
        ];
        let ids: Vec<ElementId> = walls.iter().map(|(id, _, _)| ElementId(*id)).collect();
        let lookup = lookup_for(&walls);
        let err = resolve_wall_loop(&ids, DEFAULT_WALL_LOOP_TOLERANCE, lookup).unwrap_err();
        assert_eq!(err, FoundationError::WallLoopOpen);
    }

    #[test]
    fn resolve_wall_loop_tolerance_absorbs_small_fp_noise() {
        // Tiny gap between wall 10 end and wall 11 start (0.5 mm).
        let walls = vec![
            (10, DVec2::new(0.0, 0.0), DVec2::new(1.0, 0.0)),
            (11, DVec2::new(1.0 + 5.0e-4, 0.0), DVec2::new(1.0, 1.0)),
            (12, DVec2::new(1.0, 1.0), DVec2::new(0.0, 1.0)),
            (13, DVec2::new(0.0, 1.0), DVec2::new(0.0, 0.0)),
        ];
        let ids: Vec<ElementId> = walls.iter().map(|(id, _, _)| ElementId(*id)).collect();
        let lookup = lookup_for(&walls);
        let polyline =
            resolve_wall_loop(&ids, DEFAULT_WALL_LOOP_TOLERANCE, lookup).unwrap();
        assert_eq!(polyline.len(), 4);
    }

    #[test]
    fn resolve_wall_loop_world_lookup_finds_walls() {
        // Build a Bevy world holding the four wall entities and
        // verify `lookup_wall_endpoints` returns the right pairs.
        let mut world = World::new();
        for (id, a, b) in unit_square_walls() {
            world.spawn((ElementId(id), WallEndpoints::new(a, b)));
        }
        let ep = lookup_wall_endpoints(&world, ElementId(11)).unwrap();
        assert_eq!(ep, (DVec2::new(1.0, 0.0), DVec2::new(1.0, 1.0)));
    }

    #[test]
    fn wall_endpoints_round_trip_through_json() {
        let ep = WallEndpoints::new(DVec2::new(0.5, -1.0), DVec2::new(2.5, 4.0));
        let s = serde_json::to_string(&ep).unwrap();
        let back: WallEndpoints = serde_json::from_str(&s).unwrap();
        assert_eq!(back, ep);
    }
}

#[cfg(test)]
mod typereg_tests {
    use super::*;
    use crate::capability_registry::AuthoredEntityFactory;
    use crate::plugins::modeling::dependency_graph::EntityDependencies;
    use bevy::prelude::*;

    #[test]
    fn foundation_factory_polyline_footprint_declares_no_edges() {
        let mut world = World::new();
        let entity = world
            .spawn((
                ElementId(100),
                Foundation::polyline(
                    vec![
                        DVec2::new(0.0, 0.0),
                        DVec2::new(10.0, 0.0),
                        DVec2::new(10.0, 8.0),
                        DVec2::new(0.0, 8.0),
                    ],
                    0.0,
                    0.3,
                    1.0,
                ),
            ))
            .id();

        let edges = FoundationFactory.dependency_edges(&world, entity);
        assert_eq!(
            edges,
            EntityDependencies::empty(),
            "Polyline footprint declares no structural edges; perimeter is self-contained"
        );
    }

    #[test]
    fn foundation_factory_wall_loop_footprint_declares_one_edge_per_wall() {
        let mut world = World::new();
        let walls = vec![
            ElementId(201),
            ElementId(202),
            ElementId(203),
            ElementId(204),
        ];
        let entity = world
            .spawn((
                ElementId(101),
                Foundation {
                    footprint: FoundationFootprint::WallLoop(walls.clone()),
                    floor_datum: 0.0,
                    below_grade_margin: 0.3,
                    sample_spacing: 1.0,
                },
            ))
            .id();

        let edges = FoundationFactory.dependency_edges(&world, entity);
        let expected = walls
            .iter()
            .fold(EntityDependencies::empty(), |acc, w| {
                acc.with_edge(*w, "foundation_wall_loop")
            });
        assert_eq!(edges, expected);
    }

    #[test]
    fn foundation_factory_returns_empty_when_component_missing() {
        let mut world = World::new();
        let entity = world.spawn(ElementId(102)).id();
        let edges = FoundationFactory.dependency_edges(&world, entity);
        assert_eq!(edges, EntityDependencies::empty());
    }
}
